<?php

namespace Database\Seeders;

use App\Models\tms\TMSEquipment;
use Illuminate\Database\Seeder;

class EquipmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $equipmentList = [
            ["equipment_name" => "Küçük Takım Çantası"],
            ["equipment_name" => "Büyük Boy Takım Çantası"],
            ["equipment_name" => "Vida çantası"],
            ["equipment_name" => "Yapıştırıcı"],
            ["equipment_name" => "Kısa Lokma 13'lük"],
            ["equipment_name" => "Kısa Lokma 10'luk"],
            ["equipment_name" => "Kısa Lokma 8'lük"],
            ["equipment_name" => "Kısa Lokma 7'lük"],
            ["equipment_name" => "Bosch Şarjlı (Batarya ve Şarj takımı)"],
            ["equipment_name" => "Bosch Hilti Duvar Delici"],
            ["equipment_name" => "Mac Allister Şarjlı"],
            ["equipment_name" => "Einhell Şarjlı (Batarya ve Şarj takımı)"],
            ["equipment_name" => "Su Terazisi"],
            ["equipment_name" => "Kıl Testere"],
            ["equipment_name" => "Yan keski"],
            ["equipment_name" => "Kargaburun"],
            ["equipment_name" => "Pense"],
            ["equipment_name" => "Şerit Metre"],
            ["equipment_name" => "Yıldız Tornavida Çeşitli Ebatlarda"],
            ["equipment_name" => "Düz Tornavida Çeşitli Ebatlarda"],
            ["equipment_name" => "Avuçiçi Tornavida"],
            ["equipment_name" => "Bosch Matkap Uç Takımı"],
            ["equipment_name" => "Çekiç"],
            ["equipment_name" => "Alyan Takımı"],
            ["equipment_name" => "Maket Bıçağı"],
            ["equipment_name" => "Maket Bıçağı Yedek Uç (PAKET)"],
            ["equipment_name" => "15 cm Uzun Yıldız Matkap Şarjlı Uç"],
            ["equipment_name" => "14x15 Anahtar"],
            ["equipment_name" => "10x11 Anahtar"],
            ["equipment_name" => "Apeks"],
            ["equipment_name" => "Uzun Lokma"],
            ["equipment_name" => "Küçük Takım Çantası"],
            ["equipment_name" => "Büyük Boy Takım Çantası"],
            ["equipment_name" => "Vida Kutusu"],
            ["equipment_name" => "Takım Çantası"],
            ["equipment_name" => "Bosch Matkap Uç Takımı"],
            ["equipment_name" => "Yapıştırıcı"],
            ["equipment_name" => "13'lük Lokma Tornavida"],
            ["equipment_name" => "Kısa Lokma 13'lük"],
            ["equipment_name" => "Kısa Lokma 8'lük"],
            ["equipment_name" => "Bosch Şarjlı (Batarya ve Şarj takımı)"],
            ["equipment_name" => "Bosch Hilti Duvar Delici"],
            ["equipment_name" => "Mac Allister Şarjlı (Batarya ve Şarj takımı)"],
            ["equipment_name" => "Erbauer Şarjlı (Batarya ve Şarj takımı)"],
            ["equipment_name" => "Su Terazisi"],
            ["equipment_name" => "Yan keski"],
            ["equipment_name" => "Kargaburun"],
            ["equipment_name" => "Pense"],
            ["equipment_name" => "Şerit Metre"],
            ["equipment_name" => "Avuçiçi Tornavida"],
            ["equipment_name" => "Avuçiçi Tornavida"],
            ["equipment_name" => "Yıldız Tornavida Çeşitli Ebatlarda"],
            ["equipment_name" => "Düz Tornavida Çeşitli Ebatlarda"],
            ["equipment_name" => "Matkap Uç Seti"],
            ["equipment_name" => "Çekiç"],
            ["equipment_name" => "Alyan Takımı"],
            ["equipment_name" => "Maket Bıçağı"],
            ["equipment_name" => "Maket Bıçağı Yedek Uç (PAKET)"],
            ["equipment_name" => "Kontrol Kalemi"],
            ["equipment_name" => "Rötüş Kalemi"],
            ["equipment_name" => "Büyük Boy Takım Çantası"],
            ["equipment_name" => "Stanley Darbeli Şarjlı Matkap (Batarya ve Şarj takımı)"],
            ["equipment_name" => "Su Terazisi"],
            ["equipment_name" => "Pense"],
            ["equipment_name" => "Yıldız Tornavida Çeşitli Ebatlarda"],
            ["equipment_name" => "Düz Tornavida Çeşitli Ebatlarda"],
            ["equipment_name" => "Çekiç"],
            ["equipment_name" => "Alyan Takımı"],
            ["equipment_name" => "14x15 Anahtar"],
            ["equipment_name" => "12x13 Anahtar"],
            ["equipment_name" => "Küçük Takım Çantası"],
            ["equipment_name" => "Büyük Boy Takım Çantası"],
            ["equipment_name" => "Lokma Takımı Komple"],
            ["equipment_name" => "RTR Max elektrikli Matkap"],
            ["equipment_name" => "Stanley Darbeli Şarjlı Matkap (Batarya ve Şarj takımı)"],
            ["equipment_name" => "Şerit Metre"],
            ["equipment_name" => "Düz Tornavida"],
            ["equipment_name" => "Avuçiçi Tornavida"],
            ["equipment_name" => "Çekiç"],
            ["equipment_name" => "Maket Bıçağı"],
            ["equipment_name" => "10 cm Uzun Yıldız Matkap Şarjlı Uç"],
            ["equipment_name" => "5 cm Uzun Yıldız Matkap Şarjlı Uç"],
            ["equipment_name" => "Küçük Takım Çantası"],
            ["equipment_name" => "Büyük Boy Takım Çantası"],
            ["equipment_name" => "Einhell Şarjlı (Batarya ve Şarj takımı)"],
            ["equipment_name" => "Lokma Takımı Komple"],
            ["equipment_name" => "Stanley Darbeli Şarjlı Matkap (Batarya ve Şarj takımı)"],
            ["equipment_name" => "RTR Max Elektrikli Matkap"],
            ["equipment_name" => "Şerit Metre"],
            ["equipment_name" => "Yıldız Tornavida"],
            ["equipment_name" => "Düz Tornavida"],
            ["equipment_name" => "Çekiç"],
            ["equipment_name" => "Maket Bıçağı"],
            ["equipment_name" => "5 cm Uzun Yıldız Matkap Şarjlı Uç"],
            ["equipment_name" => "8 cm Uzun Yıldız Matkap Şarjlı Uç"],
            ["equipment_name" => "Büyük Boy Takım Çantası"],
            ["equipment_name" => "Kısa Lokma 13'lük"],
            ["equipment_name" => "Kısa Lokma 11'luk"],
            ["equipment_name" => "Bosch Şarjlı (Batarya ve Şarj takımı)"],
            ["equipment_name" => "RTR Max elektrikli Matkap"],
            ["equipment_name" => "Mac Allister Şarjlı"],
            ["equipment_name" => "Pense"],
            ["equipment_name" => "Yıldız Tornavida Çeşitli Ebatlarda"],
            ["equipment_name" => "Düz Tornavida Çeşitli Ebatlarda"],
            ["equipment_name" => "Avuçiçi Tornavida"],
            ["equipment_name" => "Bosch Matkap Uç Takımı"],
            ["equipment_name" => "Çekiç"],
            ["equipment_name" => "Alyan Takımı"],
            ["equipment_name" => "Maket Bıçağı"],
            ["equipment_name" => "Maket Bıçağı Yedek Uç (Paket)"],
            ["equipment_name" => "15 cm Uzun Yıldız Matkap Şarjlı Uç"],
            ["equipment_name" => "14x15 Anahtar"],
            ["equipment_name" => "12x13 Anahtar"],
            ["equipment_name" => "10 cm Uzun Yıldız Matkap Şarjlı Uç"],
            ["equipment_name" => "5 cm Uzun Yıldız Matkap Şarjlı Uç"],
            ["equipment_name" => "10'luk Matkap Delici uç"],
            ["equipment_name" => "5'lik Matkap Delici uç"],
            ["equipment_name" => "Rötüş Kalemi"],
            ["equipment_name" => "Şerit Metre"],
            ["equipment_name" => "Su Terazisi"],
            ["equipment_name" => "Büyük Boy Takım Çantası"],
            ["equipment_name" => "Kısa Lokma 13'lük"],
            ["equipment_name" => "Kısa Lokma 11'luk"],
            ["equipment_name" => "Bosch Şarjlı (Batarya ve Şarj takımı)"],
            ["equipment_name" => "Mac Allister Şarjlı (Batarya ve Şarj takımı)"],
            ["equipment_name" => "Pense"],
            ["equipment_name" => "Şerit Metre"],
            ["equipment_name" => "Yıldız Tornavida Çeşitli Ebatlarda"],
            ["equipment_name" => "Düz Tornavida Çeşitli Ebatlarda"],
            ["equipment_name" => "Avuçiçi Tornavida"],
            ["equipment_name" => "Bosch Matkap Uç Takımı"],
            ["equipment_name" => "Çekiç"],
            ["equipment_name" => "Alyan Takımı"],
            ["equipment_name" => "Maket Bıçağı"],
            ["equipment_name" => "Maket Bıçağı Yedek Uç (paket)"],
            ["equipment_name" => "15 cm Uzun Yıldız Matkap Şarjlı Uç"],
            ["equipment_name" => "12x13 Anahtar"],
            ["equipment_name" => "14x15 Anahtar"],
            ["equipment_name" => "10 cm Uzun Yıldız Matkap Şarjlı Uç"],
            ["equipment_name" => "5 cm Uzun Yıldız Matkap Şarjlı Uç"],
            ["equipment_name" => "10'luk Matkap Delici uç"],
            ["equipment_name" => "6'lik Matkap Delici uç"],
            ["equipment_name" => "Rötüş Kalemi"],
            ["equipment_name" => "Kısa Merdiven "],
            ["equipment_name" => "Su Terazisi"],
            ["equipment_name" => "Vida Kutusu"],
            ["equipment_name" => "Takım Çantası"],
            ["equipment_name" => "Erbauer Şarjlı (Batarya ve Şarj takımı)"],
            ["equipment_name" => "Stanley Darbeli Şarjlı Matkap (Batarya ve Şarj takımı)"],
            ["equipment_name" => "Su Terazisi"],
            ["equipment_name" => "Pense"],
            ["equipment_name" => "Şerit Metre"],
            ["equipment_name" => "Avuçiçi Tornavida"],
            ["equipment_name" => "Yıldız Tornavida"],
            ["equipment_name" => "Düz Tornavida"],
            ["equipment_name" => "Çekiç"],
            ["equipment_name" => "Merdiven"],
            ["equipment_name" => "12x13 Anahtar"],
            ["equipment_name" => "Büyük Boy Takım Çantası"],
            ["equipment_name" => "Vida çantası"],
            ["equipment_name" => "Bosch Şarjlı (Batarya ve Şarj takımı)"],
            ["equipment_name" => "Stanley Darbeli Şarjlı Matkap (Batarya ve Şarj takımı) "],
            ["equipment_name" => "Erbauer Şarjlı (Batarya ve Şarj takımı)"],
            ["equipment_name" => "Su Terazisi"],
            ["equipment_name" => "Pense"],
            ["equipment_name" => "Şerit Metre"],
            ["equipment_name" => "Yıldız Tornavida"],
            ["equipment_name" => "Düz Tornavida"],
            ["equipment_name" => "Avuçiçi Tornavida"],
            ["equipment_name" => "Çekiç"],
            ["equipment_name" => "Tokmak"],
            ["equipment_name" => "12x13 Anahtar"]
        ];
        TMSEquipment::insert($equipmentList);
    }
}
