<?php

namespace Database\Seeders;

use App\Models\TaxDepartment;
use Illuminate\Database\Seeder;

class TaxDepartmentSeeder extends Seeder
{
    public function run()
    {
        $taxDepartmentLists = [
            ['id' => 1, 'district_id' => 15, 'name' => 'Adana İhtisas Vergi Dairesi Müdürlüğü'],
            ['id' => 2, 'district_id' => 15, 'name' => '5 Ocak Vergi Dairesi Müdürlüğü'],
            ['id' => 3, 'district_id' => 15, 'name' => 'Yüreğir Vergi Dairesi Müdürlüğü'],
            ['id' => 4, 'district_id' => 15, 'name' => 'Seyhan Vergi Dairesi Müdürlüğü'],
            ['id' => 5, 'district_id' => 15, 'name' => 'Ziyapaşa Vergi Dairesi Müdürlüğü'],
            ['id' => 6, 'district_id' => 15, 'name' => 'Çukurova Vergi Dairesi Müdürlüğü'],
            ['id' => 7, 'district_id' => 2, 'name' => 'Ceyhan Vergi Dairesi Müdürlüğü'],
            ['id' => 8, 'district_id' => 8, 'name' => 'Kozan Vergi Dairesi Müdürlüğü'],
            ['id' => 9, 'district_id' => 7, 'name' => 'Karataş Vergi Dairesi Müdürlüğü'],
            ['id' => 10, 'district_id' => 4, 'name' => 'Feke Malmüdürlüğü'],
            ['id' => 11, 'district_id' => 6, 'name' => 'Karaisalı Malmüdürlüğü'],
            ['id' => 12, 'district_id' => 9, 'name' => 'Pozantı Malmüdürlüğü'],
            ['id' => 13, 'district_id' => 10, 'name' => 'Saimbeyli Malmüdürlüğü'],
            ['id' => 14, 'district_id' => 13, 'name' => 'Tufanbeyli Malmüdürlüğü'],
            ['id' => 15, 'district_id' => 14, 'name' => 'Yumurtalık Malmüdürlüğü'],
            ['id' => 16, 'district_id' => 1, 'name' => 'Aladağ Malmüdürlüğü'],
            ['id' => 17, 'district_id' => 5, 'name' => 'İmamoğlu Malmüdürlüğü'],
            ['id' => 18, 'district_id' => 21, 'name' => 'Adıyaman Vergi Dairesi Müdürlüğü'],
            ['id' => 19, 'district_id' => 20, 'name' => 'Kahta Vergi Dairesi Müdürlüğü'],
            ['id' => 20, 'district_id' => 16, 'name' => 'Besni Malmüdürlüğü'],
            ['id' => 21, 'district_id' => 17, 'name' => 'Çelikhan Malmüdürlüğü'],
            ['id' => 22, 'district_id' => 18, 'name' => 'Gerger Malmüdürlüğü'],
            ['id' => 23, 'district_id' => 19, 'name' => 'Gölbaşı Malmüdürlüğü'],
            ['id' => 24, 'district_id' => 22, 'name' => 'Samsat Malmüdürlüğü'],
            ['id' => 25, 'district_id' => 23, 'name' => 'Sincik Malmüdürlüğü'],
            ['id' => 26, 'district_id' => 24, 'name' => 'Tut Malmüdürlüğü'],
            ['id' => 27, 'district_id' => 38, 'name' => 'Tınaztepe Vergi Dairesi Müdürlüğü'],
            ['id' => 28, 'district_id' => 38, 'name' => 'Kocatepe Vergi Dairesi Müdürlüğü'],
            ['id' => 29, 'district_id' => 31, 'name' => 'Dinar Vergi Dairesi Müdürlüğü'],
            ['id' => 30, 'district_id' => 27, 'name' => 'Bolvadin Vergi Dairesi Müdürlüğü'],
            ['id' => 31, 'district_id' => 32, 'name' => 'Emirdağ Vergi Dairesi Müdürlüğü'],
            ['id' => 32, 'district_id' => 39, 'name' => 'Sandıklı Vergi Dairesi Müdürlüğü'],
            ['id' => 33, 'district_id' => 36, 'name' => 'İscehisar Vergi Dairesi Müdürlüğü'],
            ['id' => 34, 'district_id' => 28, 'name' => 'Çay Vergi Dairesi Müdürlüğü'],
            ['id' => 35, 'district_id' => 30, 'name' => 'Dazkırı Malmüdürlüğü'],
            ['id' => 36, 'district_id' => 35, 'name' => 'İhsaniye Malmüdürlüğü'],
            ['id' => 37, 'district_id' => 40, 'name' => 'Sinanpaşa Malmüdürlüğü'],
            ['id' => 38, 'district_id' => 41, 'name' => 'Sultandağı Malmüdürlüğü'],
            ['id' => 39, 'district_id' => 42, 'name' => 'Şuhut Malmüdürlüğü'],
            ['id' => 40, 'district_id' => 25, 'name' => 'Başmakçı Malmüdürlüğü'],
            ['id' => 41, 'district_id' => 26, 'name' => 'Bayat Malmüdürlüğü'],
            ['id' => 42, 'district_id' => 29, 'name' => 'Çobanlar Malmüdürlüğü'],
            ['id' => 43, 'district_id' => 33, 'name' => 'Evciler Malmüdürlüğü'],
            ['id' => 44, 'district_id' => 34, 'name' => 'Hocalar Malmüdürlüğü'],
            ['id' => 45, 'district_id' => 37, 'name' => 'Kızılören Malmüdürlüğü'],
            ['id' => 46, 'district_id' => 55, 'name' => 'Ağrı Vergi Dairesi Müdürlüğü'],
            ['id' => 47, 'district_id' => 44, 'name' => 'Doğubeyazıt Vergi Dairesi Müdürlüğü'],
            ['id' => 48, 'district_id' => 48, 'name' => 'Patnos Vergi Dairesi Müdürlüğü'],
            ['id' => 49, 'district_id' => 43, 'name' => 'Diyadin Malmüdürlüğü'],
            ['id' => 50, 'district_id' => 45, 'name' => 'Eleşkirt Malmüdürlüğü'],
            ['id' => 51, 'district_id' => 46, 'name' => 'Hamur Malmüdürlüğü'],
            ['id' => 52, 'district_id' => 49, 'name' => 'Taşlıçay Malmüdürlüğü'],
            ['id' => 53, 'district_id' => 50, 'name' => 'Tutak Malmüdürlüğü'],
            ['id' => 54, 'district_id' => 62, 'name' => 'Amasya Vergi Dairesi Müdürlüğü'],
            ['id' => 55, 'district_id' => 63, 'name' => 'Merzifon Vergi Dairesi Müdürlüğü'],
            ['id' => 56, 'district_id' => 60, 'name' => 'Gümüşhacıköy Vergi Dairesi Müdürlüğü'],
            ['id' => 57, 'district_id' => 65, 'name' => 'Taşova Vergi Dairesi Müdürlüğü'],
            ['id' => 58, 'district_id' => 64, 'name' => 'Suluova Vergi Dairesi Müdürlüğü'],
            ['id' => 59, 'district_id' => 59, 'name' => 'Göynücek Malmüdürlüğü'],
            ['id' => 60, 'district_id' => 61, 'name' => 'Hamamözü Malmüdürlüğü'],
            ['id' => 61, 'district_id' => 90, 'name' => 'Anadolu İhtisas Vergi Dairesi Müdürlüğü'],
            ['id' => 62, 'district_id' => 90, 'name' => 'Ankara İhtisas Vergi Dairesi Müdürlüğü'],
            ['id' => 63, 'district_id' => 90, 'name' => 'Veraset ve Harçlar Vergi Dairesi Müdürlüğü'],
            ['id' => 64, 'district_id' => 90, 'name' => 'Kavaklıdere Vergi Dairesi Müdürlüğü'],
            ['id' => 65, 'district_id' => 90, 'name' => 'Maltepe Vergi Dairesi Müdürlüğü'],
            ['id' => 66, 'district_id' => 90, 'name' => 'Yenimahalle Vergi Dairesi Müdürlüğü'],
            ['id' => 67, 'district_id' => 90, 'name' => 'Çankaya Vergi Dairesi Müdürlüğü'],
            ['id' => 68, 'district_id' => 90, 'name' => 'Kızılbey Vergi Dairesi Müdürlüğü'],
            ['id' => 69, 'district_id' => 90, 'name' => 'Mithatpaşa Vergi Dairesi Müdürlüğü'],
            ['id' => 70, 'district_id' => 90, 'name' => 'Ulus Vergi Dairesi Müdürlüğü'],
            ['id' => 71, 'district_id' => 90, 'name' => 'Yıldırım Beyazıt Vergi Dairesi Müdürlüğü'],
            ['id' => 72, 'district_id' => 90, 'name' => 'Seğmenler Vergi Dairesi Müdürlüğü'],
            ['id' => 73, 'district_id' => 90, 'name' => 'Dikimevi Vergi Dairesi Müdürlüğü'],
            ['id' => 74, 'district_id' => 90, 'name' => 'Doğanbey Vergi Dairesi Müdürlüğü'],
            ['id' => 75, 'district_id' => 90, 'name' => 'Yeğenbey Vergi Dairesi Müdürlüğü'],
            ['id' => 76, 'district_id' => 90, 'name' => 'Hitit Vergi Dairesi Müdürlüğü'],
            ['id' => 77, 'district_id' => 90, 'name' => 'Yahya Galip Vergi Dairesi Müdürlüğü'],
            ['id' => 78, 'district_id' => 90, 'name' => 'Muhammet Karagüzel Vergi Dairesi Müdürlüğü'],
            ['id' => 79, 'district_id' => 90, 'name' => 'Ostim Vergi Dairesi Müdürlüğü'],
            ['id' => 80, 'district_id' => 90, 'name' => 'Gölbaşı Vergi Dairesi Müdürlüğü'],
            ['id' => 81, 'district_id' => 90, 'name' => 'Sincan Vergi Dairesi Müdürlüğü'],
            ['id' => 82, 'district_id' => 90, 'name' => 'Dışkapı Vergi Dairesi Müdürlüğü'],
            ['id' => 83, 'district_id' => 90, 'name' => 'Etimesgut Vergi Dairesi Müdürlüğü'],
            ['id' => 84, 'district_id' => 90, 'name' => 'Başkent Vergi Dairesi Müdürlüğü'],
            ['id' => 85, 'district_id' => 90, 'name' => 'Cumhuriyet Vergi Dairesi Müdürlüğü'],
            ['id' => 86, 'district_id' => 90, 'name' => 'Keçiören Vergi Dairesi Müdürlüğü'],
            ['id' => 87, 'district_id' => 80, 'name' => 'Kahramankazan Vergi Dairesi Müdürlüğü'],
            ['id' => 88, 'district_id' => 86, 'name' => 'Polatlı Vergi Dairesi Müdürlüğü'],
            ['id' => 89, 'district_id' => 89, 'name' => 'Şereflikoçhisar Vergi Dairesi Müdürlüğü'],
            ['id' => 90, 'district_id' => 70, 'name' => 'Beypazarı Vergi Dairesi Müdürlüğü'],
            ['id' => 91, 'district_id' => 73, 'name' => 'Çubuk Vergi Dairesi Müdürlüğü'],
            ['id' => 92, 'district_id' => 79, 'name' => 'Haymana Vergi Dairesi Müdürlüğü'],
            ['id' => 93, 'district_id' => 74, 'name' => 'Elmadağ Vergi Dairesi Müdürlüğü'],
            ['id' => 94, 'district_id' => 68, 'name' => 'Ayaş Malmüdürlüğü'],
            ['id' => 95, 'district_id' => 69, 'name' => 'Balâ Malmüdürlüğü'],
            ['id' => 96, 'district_id' => 71, 'name' => 'Çamlıdere Malmüdürlüğü'],
            ['id' => 97, 'district_id' => 78, 'name' => 'Güdül Malmüdürlüğü'],
            ['id' => 98, 'district_id' => 81, 'name' => 'Kalecik Malmüdürlüğü'],
            ['id' => 99, 'district_id' => 83, 'name' => 'Kızılcahamam Malmüdürlüğü'],
            ['id' => 100, 'district_id' => 85, 'name' => 'Nallıhan Malmüdürlüğü'],
            ['id' => 101, 'district_id' => 66, 'name' => 'Akyurt Malmüdürlüğü'],
            ['id' => 102, 'district_id' => 76, 'name' => 'Evren Malmüdürlüğü'],
            ['id' => 103, 'district_id' => 108, 'name' => 'Üçkapılar Vergi Dairesi Müdürlüğü'],
            ['id' => 104, 'district_id' => 108, 'name' => 'Kalekapı Vergi Dairesi Müdürlüğü'],
            ['id' => 105, 'district_id' => 108, 'name' => 'Muratpaşa Vergi Dairesi Müdürlüğü'],
            ['id' => 106, 'district_id' => 108, 'name' => 'Düden Vergi Dairesi Müdürlüğü'],
            ['id' => 107, 'district_id' => 108, 'name' => 'Antalya Kurumlar Vergi Dairesi Müdürlüğü'],
            ['id' => 108, 'district_id' => 108, 'name' => 'Antalya İhtisas Vergi Dairesi Müdürlüğü'],
            ['id' => 109, 'district_id' => 93, 'name' => 'Alanya Vergi Dairesi Müdürlüğü'],
            ['id' => 110, 'district_id' => 109, 'name' => 'Serik Vergi Dairesi Müdürlüğü'],
            ['id' => 111, 'district_id' => 107, 'name' => 'Manavgat Vergi Dairesi Müdürlüğü'],
            ['id' => 112, 'district_id' => 96, 'name' => 'Elmalı Vergi Dairesi Müdürlüğü'],
            ['id' => 113, 'district_id' => 102, 'name' => 'Kemer Vergi Dairesi Müdürlüğü'],
            ['id' => 114, 'district_id' => 106, 'name' => 'Kumluca Vergi Dairesi Müdürlüğü'],
            ['id' => 115, 'district_id' => 91, 'name' => 'Akseki Malmüdürlüğü'],
            ['id' => 116, 'district_id' => 97, 'name' => 'Finike Malmüdürlüğü'],
            ['id' => 117, 'district_id' => 97, 'name' => 'Gazipaşa Malmüdürlüğü'],
            ['id' => 118, 'district_id' => 99, 'name' => 'Gündoğmuş Malmüdürlüğü'],
            ['id' => 119, 'district_id' => 101, 'name' => 'Kaş Malmüdürlüğü'],
            ['id' => 120, 'district_id' => 105, 'name' => 'Korkuteli Malmüdürlüğü'],
            ['id' => 121, 'district_id' => 94, 'name' => 'Demre Malmüdürlüğü'],
            ['id' => 122, 'district_id' => 100, 'name' => 'İbradı Malmüdürlüğü'],
            ['id' => 123, 'district_id' => 121, 'name' => 'Artvin Vergi Dairesi Müdürlüğü'],
            ['id' => 124, 'district_id' => 119, 'name' => 'Hopa Vergi Dairesi Müdürlüğü'],
            ['id' => 125, 'district_id' => 117, 'name' => 'Arhavi Vergi Dairesi Müdürlüğü'],
            ['id' => 126, 'district_id' => 116, 'name' => 'Ardanuç Malmüdürlüğü'],
            ['id' => 127, 'district_id' => 118, 'name' => 'Borçka Malmüdürlüğü'],
            ['id' => 128, 'district_id' => 123, 'name' => 'Şavşat Malmüdürlüğü'],
            ['id' => 129, 'district_id' => 124, 'name' => 'Yusufeli Malmüdürlüğü'],
            ['id' => 130, 'district_id' => 122, 'name' => 'Murgul Malmüdürlüğü'],
            ['id' => 131, 'district_id' => 129, 'name' => 'Efeler Vergi Dairesi Müdürlüğü'],
            ['id' => 132, 'district_id' => 129, 'name' => 'Güzelhisar Vergi Dairesi Müdürlüğü'],
            ['id' => 133, 'district_id' => 138, 'name' => 'Nazilli Vergi Dairesi Müdürlüğü'],
            ['id' => 134, 'district_id' => 139, 'name' => 'Söke Vergi Dairesi Müdürlüğü'],
            ['id' => 135, 'district_id' => 127, 'name' => 'Çine Vergi Dairesi Müdürlüğü'],
            ['id' => 136, 'district_id' => 130, 'name' => 'Germencik Vergi Dairesi Müdürlüğü'],
            ['id' => 137, 'district_id' => 136, 'name' => 'Kuşadası Vergi Dairesi Müdürlüğü'],
            ['id' => 138, 'district_id' => 128, 'name' => 'Didim Vergi Dairesi Müdürlüğü'],
            ['id' => 139, 'district_id' => 125, 'name' => 'Bozdoğan Malmüdürlüğü'],
            ['id' => 140, 'district_id' => 132, 'name' => 'Karacasu Malmüdürlüğü'],
            ['id' => 141, 'district_id' => 134, 'name' => 'Koçarlı Malmüdürlüğü'],
            ['id' => 142, 'district_id' => 137, 'name' => 'Kuyucak Malmüdürlüğü'],
            ['id' => 143, 'district_id' => 140, 'name' => 'Sultanhisar Malmüdürlüğü'],
            ['id' => 144, 'district_id' => 141, 'name' => 'Yenipazar Malmüdürlüğü'],
            ['id' => 145, 'district_id' => 126, 'name' => 'Buharkent Malmüdürlüğü'],
            ['id' => 146, 'district_id' => 131, 'name' => 'İncirliova Malmüdürlüğü'],
            ['id' => 147, 'district_id' => 133, 'name' => 'Karpuzlu Malmüdürlüğü'],
            ['id' => 148, 'district_id' => 135, 'name' => 'Köşk Malmüdürlüğü'],
            ['id' => 149, 'district_id' => 142, 'name' => 'Karesi Vergi Dairesi Müdürlüğü'],
            ['id' => 150, 'district_id' => 142, 'name' => 'Kurtdereli Vergi Dairesi Müdürlüğü'],
            ['id' => 151, 'district_id' => 143, 'name' => 'Ayvalık Vergi Dairesi Müdürlüğü'],
            ['id' => 152, 'district_id' => 145, 'name' => 'Bandırma Vergi Dairesi Müdürlüğü'],
            ['id' => 153, 'district_id' => 147, 'name' => 'Burhaniye Vergi Dairesi Müdürlüğü'],
            ['id' => 154, 'district_id' => 149, 'name' => 'Edremit Vergi Dairesi Müdürlüğü'],
            ['id' => 155, 'district_id' => 152, 'name' => 'Gönen Vergi Dairesi Müdürlüğü'],
            ['id' => 156, 'district_id' => 161, 'name' => 'Susurluk Vergi Dairesi Müdürlüğü'],
            ['id' => 157, 'district_id' => 150, 'name' => 'Erdek Vergi Dairesi Müdürlüğü'],
            ['id' => 158, 'district_id' => 146, 'name' => 'Bigadiç Vergi Dairesi Müdürlüğü'],
            ['id' => 159, 'district_id' => 160, 'name' => 'Sındırgı Vergi Dairesi Müdürlüğü'],
            ['id' => 160, 'district_id' => 148, 'name' => 'Dursunbey Vergi Dairesi Müdürlüğü'],
            ['id' => 161, 'district_id' => 144, 'name' => 'Balya Malmüdürlüğü'],
            ['id' => 162, 'district_id' => 153, 'name' => 'Havran Malmüdürlüğü'],
            ['id' => 163, 'district_id' => 154, 'name' => 'İvrindi Malmüdürlüğü'],
            ['id' => 164, 'district_id' => 156, 'name' => 'Kepsut Malmüdürlüğü'],
            ['id' => 165, 'district_id' => 157, 'name' => 'Manyas Malmüdürlüğü'],
            ['id' => 166, 'district_id' => 159, 'name' => 'Savaştepe Malmüdürlüğü'],
            ['id' => 167, 'district_id' => 158, 'name' => 'Marmara Malmüdürlüğü'],
            ['id' => 168, 'district_id' => 151, 'name' => 'Gömeç Malmüdürlüğü'],
            ['id' => 169, 'district_id' => 178, 'name' => 'Bilecik Vergi Dairesi Müdürlüğü'],
            ['id' => 170, 'district_id' => 175, 'name' => 'Bozüyük Vergi Dairesi Müdürlüğü'],
            ['id' => 171, 'district_id' => 176, 'name' => 'Gölpazarı Malmüdürlüğü'],
            ['id' => 172, 'district_id' => 179, 'name' => 'Osmaneli Malmüdürlüğü'],
            ['id' => 173, 'district_id' => 180, 'name' => 'Pazaryeri Malmüdürlüğü'],
            ['id' => 174, 'district_id' => 181, 'name' => 'Söğüt Malmüdürlüğü'],
            ['id' => 175, 'district_id' => 182, 'name' => 'Yenipazar Malmüdürlüğü'],
            ['id' => 176, 'district_id' => 177, 'name' => 'İnhisar Malmüdürlüğü'],
            ['id' => 177, 'district_id' => 187, 'name' => 'Bingöl Vergi Dairesi Müdürlüğü'],
            ['id' => 178, 'district_id' => 184, 'name' => 'Genç Malmüdürlüğü'],
            ['id' => 179, 'district_id' => 185, 'name' => 'Karlıova Malmüdürlüğü'],
            ['id' => 180, 'district_id' => 186, 'name' => 'Kiğı Malmüdürlüğü'],
            ['id' => 181, 'district_id' => 188, 'name' => 'Solhan Malmüdürlüğü'],
            ['id' => 182, 'district_id' => 183, 'name' => 'Adaklı Malmüdürlüğü'],
            ['id' => 183, 'district_id' => 189, 'name' => 'Yayladere Malmüdürlüğü'],
            ['id' => 184, 'district_id' => 190, 'name' => 'Yedisu Malmüdürlüğü'],
            ['id' => 185, 'district_id' => 195, 'name' => 'Bitlis Vergi Dairesi Müdürlüğü'],
            ['id' => 186, 'district_id' => 197, 'name' => 'Tatvan Vergi Dairesi Müdürlüğü'],
            ['id' => 187, 'district_id' => 191, 'name' => 'Adilcevaz Malmüdürlüğü'],
            ['id' => 188, 'district_id' => 192, 'name' => 'Ahlat Malmüdürlüğü'],
            ['id' => 189, 'district_id' => 194, 'name' => 'Hizan Malmüdürlüğü'],
            ['id' => 190, 'district_id' => 196, 'name' => 'Mutki Malmüdürlüğü'],
            ['id' => 191, 'district_id' => 193, 'name' => 'Güroymak Malmüdürlüğü'],
            ['id' => 192, 'district_id' => 203, 'name' => 'Bolu Vergi Dairesi Müdürlüğü'],
            ['id' => 193, 'district_id' => 199, 'name' => 'Gerede Vergi Dairesi Müdürlüğü'],
            ['id' => 194, 'district_id' => 200, 'name' => 'Göynük Malmüdürlüğü'],
            ['id' => 195, 'district_id' => 201, 'name' => 'Kıbrıscık Malmüdürlüğü'],
            ['id' => 196, 'district_id' => 202, 'name' => 'Mengen Malmüdürlüğü'],
            ['id' => 197, 'district_id' => 204, 'name' => 'Mudurnu Malmüdürlüğü'],
            ['id' => 198, 'district_id' => 205, 'name' => 'Seben Malmüdürlüğü'],
            ['id' => 199, 'district_id' => 198, 'name' => 'Dörtdivan Malmüdürlüğü'],
            ['id' => 200, 'district_id' => 206, 'name' => 'Yeniçağa Malmüdürlüğü'],
            ['id' => 201, 'district_id' => 215, 'name' => 'Burdur Vergi Dairesi Müdürlüğü'],
            ['id' => 202, 'district_id' => 209, 'name' => 'Bucak Vergi Dairesi Müdürlüğü'],
            ['id' => 203, 'district_id' => 207, 'name' => 'Ağlasun Malmüdürlüğü'],
            ['id' => 204, 'district_id' => 212, 'name' => 'Gölhisar Malmüdürlüğü'],
            ['id' => 205, 'district_id' => 216, 'name' => 'Tefenni Malmüdürlüğü'],
            ['id' => 206, 'district_id' => 217, 'name' => 'Yeşilova Malmüdürlüğü'],
            ['id' => 207, 'district_id' => 213, 'name' => 'Karamanlı Malmüdürlüğü'],
            ['id' => 208, 'district_id' => 214, 'name' => 'Kemer Malmüdürlüğü'],
            ['id' => 209, 'district_id' => 208, 'name' => 'Altınyayla Malmüdürlüğü'],
            ['id' => 210, 'district_id' => 210, 'name' => 'Çavdır Malmüdürlüğü'],
            ['id' => 211, 'district_id' => 211, 'name' => 'Çeltikçi Malmüdürlüğü'],
            ['id' => 212, 'district_id' => 232, 'name' => 'Bursa İhtisas Vergi Dairesi Müdürlüğü'],
            ['id' => 213, 'district_id' => 232, 'name' => 'Osmangazi Vergi Dairesi Müdürlüğü'],
            ['id' => 214, 'district_id' => 232, 'name' => 'Yıldırım Vergi Dairesi Müdürlüğü'],
            ['id' => 215, 'district_id' => 232, 'name' => 'Çekirge Vergi Dairesi Müdürlüğü'],
            ['id' => 216, 'district_id' => 232, 'name' => 'Setbaşı Vergi Dairesi Müdürlüğü'],
            ['id' => 217, 'district_id' => 232, 'name' => 'Uludağ Vergi Dairesi Müdürlüğü'],
            ['id' => 218, 'district_id' => 232, 'name' => 'Yeşil Vergi Dairesi Müdürlüğü'],
            ['id' => 219, 'district_id' => 232, 'name' => 'Nilüfer Vergi Dairesi Müdürlüğü'],
            ['id' => 220, 'district_id' => 232, 'name' => 'Ertuğrulgazi Vergi Dairesi Müdürlüğü'],
            ['id' => 221, 'district_id' => 232, 'name' => 'Gökdere Vergi Dairesi Müdürlüğü'],
            ['id' => 222, 'district_id' => 232, 'name' => 'Bursa Veraset ve Harçlar Vergi Dairesi Müdürlüğü'],
            ['id' => 223, 'district_id' => 219, 'name' => 'Gemlik Vergi Dairesi Müdürlüğü'],
            ['id' => 224, 'district_id' => 222, 'name' => 'İnegöl Vergi Dairesi Müdürlüğü'],
            ['id' => 225, 'district_id' => 224, 'name' => 'Karacabey Vergi Dairesi Müdürlüğü'],
            ['id' => 226, 'district_id' => 228, 'name' => 'Mustafakemalpaşa Vergi Dairesi Müdürlüğü'],
            ['id' => 227, 'district_id' => 227, 'name' => 'Mudanya Vergi Dairesi Müdürlüğü'],
            ['id' => 228, 'district_id' => 231, 'name' => 'Orhangazi Vergi Dairesi Müdürlüğü'],
            ['id' => 229, 'district_id' => 223, 'name' => 'İznik Vergi Dairesi Müdürlüğü'],
            ['id' => 230, 'district_id' => 233, 'name' => 'Yenişehir Vergi Dairesi Müdürlüğü'],
            ['id' => 231, 'district_id' => 225, 'name' => 'Keles Malmüdürlüğü'],
            ['id' => 232, 'district_id' => 230, 'name' => 'Orhaneli Malmüdürlüğü'],
            ['id' => 233, 'district_id' => 221, 'name' => 'Harmancık Malmüdürlüğü'],
            ['id' => 234, 'district_id' => 218, 'name' => 'Büyükorhan Malmüdürlüğü'],
            ['id' => 235, 'district_id' => 245, 'name' => 'Çanakkale Vergi Dairesi Müdürlüğü'],
            ['id' => 236, 'district_id' => 237, 'name' => 'Biga Vergi Dairesi Müdürlüğü'],
            ['id' => 237, 'district_id' => 239, 'name' => 'Çan Vergi Dairesi Müdürlüğü'],
            ['id' => 238, 'district_id' => 242, 'name' => 'Gelibolu Vergi Dairesi Müdürlüğü'],
            ['id' => 239, 'district_id' => 235, 'name' => 'Ayvacık Malmüdürlüğü'],
            ['id' => 240, 'district_id' => 236, 'name' => 'Bayramiç Malmüdürlüğü'],
            ['id' => 241, 'district_id' => 238, 'name' => 'Bozcaada Malmüdürlüğü'],
            ['id' => 242, 'district_id' => 240, 'name' => 'Eceabat Malmüdürlüğü'],
            ['id' => 243, 'district_id' => 241, 'name' => 'Ezine Malmüdürlüğü'],
            ['id' => 244, 'district_id' => 243, 'name' => 'Gökçeada Malmüdürlüğü'],
            ['id' => 245, 'district_id' => 244, 'name' => 'Lapseki Malmüdürlüğü'],
            ['id' => 246, 'district_id' => 246, 'name' => 'Yenice Malmüdürlüğü'],
            ['id' => 247, 'district_id' => 255, 'name' => 'Çankırı Vergi Dairesi Müdürlüğü'],
            ['id' => 248, 'district_id' => 249, 'name' => 'Çerkeş Malmüdürlüğü'],
            ['id' => 249, 'district_id' => 250, 'name' => 'Eldivan Malmüdürlüğü'],
            ['id' => 250, 'district_id' => 251, 'name' => 'Ilgaz Malmüdürlüğü'],
            ['id' => 251, 'district_id' => 254, 'name' => 'Kurşunlu Malmüdürlüğü'],
            ['id' => 252, 'district_id' => 256, 'name' => 'Orta Malmüdürlüğü'],
            ['id' => 253, 'district_id' => 257, 'name' => 'Şabanözü Malmüdürlüğü'],
            ['id' => 254, 'district_id' => 258, 'name' => 'Yapraklı Malmüdürlüğü'],
            ['id' => 255, 'district_id' => 247, 'name' => 'Atkaracalar Malmüdürlüğü'],
            ['id' => 256, 'district_id' => 252, 'name' => 'Kızılırmak Malmüdürlüğü'],
            ['id' => 257, 'district_id' => 248, 'name' => 'Bayramören Malmüdürlüğü'],
            ['id' => 258, 'district_id' => 253, 'name' => 'Korgun Malmüdürlüğü'],
            ['id' => 259, 'district_id' => 267, 'name' => 'Çorum Vergi Dairesi Müdürlüğü'],
            ['id' => 260, 'district_id' => 271, 'name' => 'Sungurlu Vergi Dairesi Müdürlüğü'],
            ['id' => 261, 'district_id' => 259, 'name' => 'Alaca Malmüdürlüğü'],
            ['id' => 262, 'district_id' => 260, 'name' => 'Bayat Malmüdürlüğü'],
            ['id' => 263, 'district_id' => 263, 'name' => 'İskilip Malmüdürlüğü'],
            ['id' => 264, 'district_id' => 264, 'name' => 'Kargı Malmüdürlüğü'],
            ['id' => 265, 'district_id' => 266, 'name' => 'Mecitözü Malmüdürlüğü'],
            ['id' => 266, 'district_id' => 269, 'name' => 'Ortaköy Malmüdürlüğü'],
            ['id' => 267, 'district_id' => 270, 'name' => 'Osmancık Malmüdürlüğü'],
            ['id' => 268, 'district_id' => 261, 'name' => 'Boğazkale Malmüdürlüğü'],
            ['id' => 269, 'district_id' => 272, 'name' => 'Uğurludağ Malmüdürlüğü'],
            ['id' => 270, 'district_id' => 262, 'name' => 'Dodurga Malmüdürlüğü'],
            ['id' => 271, 'district_id' => 268, 'name' => 'Oğuzlar Malmüdürlüğü'],
            ['id' => 272, 'district_id' => 265, 'name' => 'Laçin Malmüdürlüğü'],
            ['id' => 273, 'district_id' => 287, 'name' => 'Saraylar Vergi Dairesi Müdürlüğü'],
            ['id' => 274, 'district_id' => 287, 'name' => 'Çınar Vergi Dairesi Müdürlüğü'],
            ['id' => 275, 'district_id' => 287, 'name' => 'Gökpınar Vergi Dairesi Müdürlüğü'],
            ['id' => 276, 'district_id' => 287, 'name' => 'Denizli İhtisas Vergi Dairesi Müdürlüğü'],
            ['id' => 277, 'district_id' => 287, 'name' => 'Pamukkale Vergi Dairesi Müdürlüğü'],
            ['id' => 278, 'district_id' => 289, 'name' => 'Sarayköy Vergi Dairesi Müdürlüğü'],
            ['id' => 279, 'district_id' => 273, 'name' => 'Acıpayam Vergi Dairesi Müdürlüğü'],
            ['id' => 280, 'district_id' => 291, 'name' => 'Tavas Vergi Dairesi Müdürlüğü'],
            ['id' => 281, 'district_id' => 279, 'name' => 'Buldan Vergi Dairesi Müdürlüğü'],
            ['id' => 282, 'district_id' => 280, 'name' => 'Çal Vergi Dairesi Müdürlüğü'],
            ['id' => 283, 'district_id' => 283, 'name' => 'Çivril Vergi Dairesi Müdürlüğü'],
            ['id' => 284, 'district_id' => 281, 'name' => 'Çameli Malmüdürlüğü'],
            ['id' => 285, 'district_id' => 282, 'name' => 'Çardak Malmüdürlüğü'],
            ['id' => 286, 'district_id' => 284, 'name' => 'Güney Malmüdürlüğü'],
            ['id' => 287, 'district_id' => 286, 'name' => 'Kale Malmüdürlüğü'],
            ['id' => 288, 'district_id' => 274, 'name' => 'Babadağ Malmüdürlüğü'],
            ['id' => 289, 'district_id' => 276, 'name' => 'Bekilli Malmüdürlüğü'],
            ['id' => 290, 'district_id' => 285, 'name' => 'Honaz Malmüdürlüğü'],
            ['id' => 291, 'district_id' => 290, 'name' => 'Serinhisar Malmüdürlüğü'],
            ['id' => 292, 'district_id' => 288, 'name' => 'Pamukkale Malmüdürlüğü (Akköy]'],
            ['id' => 293, 'district_id' => 275, 'name' => 'Baklan Malmüdürlüğü'],
            ['id' => 294, 'district_id' => 277, 'name' => 'Beyağaç Malmüdürlüğü'],
            ['id' => 295, 'district_id' => 278, 'name' => 'Bozkurt Malmüdürlüğü'],
            ['id' => 296, 'district_id' => 308, 'name' => 'Gökalp Vergi Dairesi Müdürlüğü'],
            ['id' => 297, 'district_id' => 308, 'name' => 'Süleyman Nazif Vergi Dairesi Müdürlüğü'],
            ['id' => 298, 'district_id' => 308, 'name' => 'Cahit Sıtkı Tarancı Vergi Dairesi Müdürlüğü'],
            ['id' => 299, 'district_id' => 299, 'name' => 'Ergani Vergi Dairesi Müdürlüğü'],
            ['id' => 300, 'district_id' => 293, 'name' => 'Bismil Vergi Dairesi Müdürlüğü'],
            ['id' => 301, 'district_id' => 294, 'name' => 'Çermik Malmüdürlüğü'],
            ['id' => 302, 'district_id' => 295, 'name' => 'Çınar Malmüdürlüğü'],
            ['id' => 303, 'district_id' => 296, 'name' => 'Çüngüş Malmüdürlüğü'],
            ['id' => 304, 'district_id' => 297, 'name' => 'Dicle Malmüdürlüğü'],
            ['id' => 305, 'district_id' => 300, 'name' => 'Hani Malmüdürlüğü'],
            ['id' => 306, 'district_id' => 301, 'name' => 'Hazro Malmüdürlüğü'],
            ['id' => 307, 'district_id' => 304, 'name' => 'Kulp Malmüdürlüğü'],
            ['id' => 308, 'district_id' => 305, 'name' => 'Lice Malmüdürlüğü'],
            ['id' => 309, 'district_id' => 306, 'name' => 'Silvan Malmüdürlüğü'],
            ['id' => 310, 'district_id' => 298, 'name' => 'Eğil Malmüdürlüğü'],
            ['id' => 311, 'district_id' => 303, 'name' => 'Kocaköy Malmüdürlüğü'],
            ['id' => 312, 'district_id' => 315, 'name' => 'Arda Vergi Dairesi Müdürlüğü'],
            ['id' => 313, 'district_id' => 315, 'name' => 'Kırkpınar Vergi Dairesi Müdürlüğü'],
            ['id' => 314, 'district_id' => 320, 'name' => 'Keşan Vergi Dairesi Müdürlüğü'],
            ['id' => 315, 'district_id' => 325, 'name' => 'Uzunköprü Vergi Dairesi Müdürlüğü'],
            ['id' => 316, 'district_id' => 318, 'name' => 'Havsa Vergi Dairesi Müdürlüğü'],
            ['id' => 317, 'district_id' => 319, 'name' => 'İpsala Vergi Dairesi Müdürlüğü'],
            ['id' => 318, 'district_id' => 317, 'name' => 'Enez Malmüdürlüğü'],
            ['id' => 319, 'district_id' => 321, 'name' => 'Lalapaşa Malmüdürlüğü'],
            ['id' => 320, 'district_id' => 322, 'name' => 'Meriç Malmüdürlüğü'],
            ['id' => 321, 'district_id' => 324, 'name' => 'Süloğlu Malmüdürlüğü'],
            ['id' => 322, 'district_id' => 334, 'name' => 'Harput Vergi Dairesi Müdürlüğü'],
            ['id' => 323, 'district_id' => 334, 'name' => 'Hazar Vergi Dairesi Müdürlüğü'],
            ['id' => 324, 'district_id' => 326, 'name' => 'Ağın Malmüdürlüğü'],
            ['id' => 325, 'district_id' => 329, 'name' => 'Baskil Malmüdürlüğü'],
            ['id' => 326, 'district_id' => 330, 'name' => 'Karakoçan Malmüdürlüğü'],
            ['id' => 327, 'district_id' => 331, 'name' => 'Keban Malmüdürlüğü'],
            ['id' => 328, 'district_id' => 333, 'name' => 'Maden Malmüdürlüğü'],
            ['id' => 329, 'district_id' => 335, 'name' => 'Palu Malmüdürlüğü'],
            ['id' => 330, 'district_id' => 336, 'name' => 'Sivrice Malmüdürlüğü'],
            ['id' => 331, 'district_id' => 328, 'name' => 'Arıcak Malmüdürlüğü'],
            ['id' => 332, 'district_id' => 332, 'name' => 'Kovancılar Malmüdürlüğü'],
            ['id' => 333, 'district_id' => 327, 'name' => 'Alacakaya Malmüdürlüğü'],
            ['id' => 334, 'district_id' => 341, 'name' => 'Fevzipaşa Vergi Dairesi Müdürlüğü'],
            ['id' => 335, 'district_id' => 337, 'name' => 'Çayırlı Malmüdürlüğü'],
            ['id' => 336, 'district_id' => 338, 'name' => 'İliç Malmüdürlüğü'],
            ['id' => 337, 'district_id' => 339, 'name' => 'Kemah Malmüdürlüğü'],
            ['id' => 338, 'district_id' => 340, 'name' => 'Kemaliye Malmüdürlüğü'],
            ['id' => 339, 'district_id' => 343, 'name' => 'Refahiye Malmüdürlüğü'],
            ['id' => 340, 'district_id' => 344, 'name' => 'Tercan Malmüdürlüğü'],
            ['id' => 341, 'district_id' => 345, 'name' => 'Üzümlü Malmüdürlüğü'],
            ['id' => 342, 'district_id' => 342, 'name' => 'Otlukbeli Malmüdürlüğü'],
            ['id' => 343, 'district_id' => 365, 'name' => 'Aziziye Vergi Dairesi Müdürlüğü'],
            ['id' => 344, 'district_id' => 365, 'name' => 'Kazımkarabekir Vergi Dairesi Müdürlüğü'],
            ['id' => 345, 'district_id' => 346, 'name' => 'Aşkale Malmüdürlüğü'],
            ['id' => 346, 'district_id' => 348, 'name' => 'Çat Malmüdürlüğü'],
            ['id' => 347, 'district_id' => 349, 'name' => 'Hınıs Malmüdürlüğü'],
            ['id' => 348, 'district_id' => 350, 'name' => 'Horasan Malmüdürlüğü'],
            ['id' => 349, 'district_id' => 351, 'name' => 'İspir Malmüdürlüğü'],
            ['id' => 350, 'district_id' => 353, 'name' => 'Karayazı Malmüdürlüğü'],
            ['id' => 351, 'district_id' => 355, 'name' => 'Narman Malmüdürlüğü'],
            ['id' => 352, 'district_id' => 356, 'name' => 'Oltu Malmüdürlüğü'],
            ['id' => 353, 'district_id' => 357, 'name' => 'Olur Malmüdürlüğü'],
            ['id' => 354, 'district_id' => 359, 'name' => 'Pasinler Malmüdürlüğü'],
            ['id' => 355, 'district_id' => 361, 'name' => 'Şenkaya Malmüdürlüğü'],
            ['id' => 356, 'district_id' => 362, 'name' => 'Tekman Malmüdürlüğü'],
            ['id' => 357, 'district_id' => 363, 'name' => 'Tortum Malmüdürlüğü'],
            ['id' => 358, 'district_id' => 352, 'name' => 'Karaçoban Malmüdürlüğü'],
            ['id' => 359, 'district_id' => 364, 'name' => 'Uzundere Malmüdürlüğü'],
            ['id' => 360, 'district_id' => 360, 'name' => 'Pazaryolu Malmüdürlüğü'],
            ['id' => 361, 'district_id' => 347, 'name' => 'Aziziye Malmüdürlüğü (Ilıca]'],
            ['id' => 362, 'district_id' => 354, 'name' => 'Köprüköy Malmüdürlüğü'],
            ['id' => 363, 'district_id' => 375, 'name' => 'Eskişehir Vergi Dairesi Başkanlığı'],
            ['id' => 364, 'district_id' => 372, 'name' => 'Mahmudiye Malmüdürlüğü'],
            ['id' => 365, 'district_id' => 374, 'name' => 'Mihalıççık Malmüdürlüğü'],
            ['id' => 366, 'district_id' => 376, 'name' => 'Sarıcakaya Malmüdürlüğü'],
            ['id' => 367, 'district_id' => 377, 'name' => 'Seyitgazi Malmüdürlüğü'],
            ['id' => 368, 'district_id' => 366, 'name' => 'Alpu Malmüdürlüğü'],
            ['id' => 369, 'district_id' => 367, 'name' => 'Beylikova Malmüdürlüğü'],
            ['id' => 370, 'district_id' => 371, 'name' => 'İnönü Malmüdürlüğü'],
            ['id' => 371, 'district_id' => 369, 'name' => 'Günyüzü Malmüdürlüğü'],
            ['id' => 372, 'district_id' => 370, 'name' => 'Han Malmüdürlüğü'],
            ['id' => 373, 'district_id' => 373, 'name' => 'Mihalgazi Malmüdürlüğü'],
            ['id' => 374, 'district_id' => 387, 'name' => 'Gaziantep İhtisas Vergi Dairesi Müdürlüğü'],
            ['id' => 375, 'district_id' => 387, 'name' => 'Suburcu Vergi Dairesi Müdürlüğü'],
            ['id' => 376, 'district_id' => 387, 'name' => 'Şehitkâmil Vergi Dairesi Müdürlüğü'],
            ['id' => 377, 'district_id' => 387, 'name' => 'Şahinbey Vergi Dairesi Müdürlüğü'],
            ['id' => 378, 'district_id' => 387, 'name' => 'Gazikent Vergi Dairesi Müdürlüğü'],
            ['id' => 379, 'district_id' => 387, 'name' => 'Kozanlı Vergi Dairesi Müdürlüğü'],
            ['id' => 380, 'district_id' => 383, 'name' => 'Nizip Vergi Dairesi Müdürlüğü'],
            ['id' => 381, 'district_id' => 381, 'name' => 'İslahiye Vergi Dairesi Müdürlüğü'],
            ['id' => 382, 'district_id' => 380, 'name' => 'Araban Malmüdürlüğü'],
            ['id' => 383, 'district_id' => 385, 'name' => 'Oğuzeli Malmüdürlüğü'],
            ['id' => 384, 'district_id' => 388, 'name' => 'Yavuzeli Malmüdürlüğü'],
            ['id' => 385, 'district_id' => 382, 'name' => 'Karkamış Malmüdürlüğü'],
            ['id' => 386, 'district_id' => 384, 'name' => 'Nurdağı Malmüdürlüğü'],
            ['id' => 387, 'district_id' => 400, 'name' => 'Giresun Vergi Dairesi Müdürlüğü'],
            ['id' => 388, 'district_id' => 390, 'name' => 'Bulancak Vergi Dairesi Müdürlüğü'],
            ['id' => 389, 'district_id' => 389, 'name' => 'Alucra Malmüdürlüğü'],
            ['id' => 390, 'district_id' => 393, 'name' => 'Dereli Malmüdürlüğü'],
            ['id' => 391, 'district_id' => 395, 'name' => 'Espiye Malmüdürlüğü'],
            ['id' => 392, 'district_id' => 396, 'name' => 'Eynesil Malmüdürlüğü'],
            ['id' => 393, 'district_id' => 397, 'name' => 'Görele Malmüdürlüğü'],
            ['id' => 394, 'district_id' => 399, 'name' => 'Keşap Malmüdürlüğü'],
            ['id' => 395, 'district_id' => 402, 'name' => 'Şebinkarahisar Malmüdürlüğü'],
            ['id' => 396, 'district_id' => 403, 'name' => 'Tirebolu Malmüdürlüğü'],
            ['id' => 397, 'district_id' => 401, 'name' => 'Piraziz Malmüdürlüğü'],
            ['id' => 398, 'district_id' => 404, 'name' => 'Yağlıdere Malmüdürlüğü'],
            ['id' => 399, 'district_id' => 392, 'name' => 'Çanakçı Malmüdürlüğü'],
            ['id' => 400, 'district_id' => 398, 'name' => 'Güce Malmüdürlüğü'],
            ['id' => 401, 'district_id' => 391, 'name' => 'Çamoluk Malmüdürlüğü'],
            ['id' => 402, 'district_id' => 394, 'name' => 'Doğankent Malmüdürlüğü'],
            ['id' => 403, 'district_id' => 408, 'name' => 'Gümüşhane Vergi Dairesi Müdürlüğü'],
            ['id' => 404, 'district_id' => 405, 'name' => 'Kelkit Malmüdürlüğü'],
            ['id' => 405, 'district_id' => 409, 'name' => 'Şiran Malmüdürlüğü'],
            ['id' => 406, 'district_id' => 410, 'name' => 'Torul Malmüdürlüğü'],
            ['id' => 407, 'district_id' => 406, 'name' => 'Köse Malmüdürlüğü'],
            ['id' => 408, 'district_id' => 407, 'name' => 'Kürtün Malmüdürlüğü'],
            ['id' => 409, 'district_id' => 412, 'name' => 'Hakkari Vergi Dairesi Müdürlüğü'],
            ['id' => 410, 'district_id' => 414, 'name' => 'Yüksekova  Vergi Dairesi Müdürlüğü'],
            ['id' => 411, 'district_id' => 411, 'name' => 'Çukurca Malmüdürlüğü'],
            ['id' => 412, 'district_id' => 413, 'name' => 'Şemdinli Malmüdürlüğü'],
            ['id' => 413, 'district_id' => 416, 'name' => '23 Temmuz Vergi Dairesi Müdürlüğü'],
            ['id' => 414, 'district_id' => 416, 'name' => 'Antakya Vergi Dairesi Müdürlüğü'],
            ['id' => 415, 'district_id' => 416, 'name' => 'Şükrükanatlı Vergi Dairesi Müdürlüğü'],
            ['id' => 416, 'district_id' => 423, 'name' => 'Sahil Vergi Dairesi Müdürlüğü'],
            ['id' => 417, 'district_id' => 423, 'name' => 'Akdeniz Vergi Dairesi Müdürlüğü'],
            ['id' => 418, 'district_id' => 423, 'name' => 'Asım Gündüz Vergi Dairesi Müdürlüğü'],
            ['id' => 419, 'district_id' => 420, 'name' => 'Dörtyol  Vergi Dairesi Müdürlüğü'],
            ['id' => 420, 'district_id' => 424, 'name' => 'Kırıkhan Vergi Dairesi Müdürlüğü'],
            ['id' => 421, 'district_id' => 427, 'name' => 'Reyhanlı Vergi Dairesi Müdürlüğü'],
            ['id' => 422, 'district_id' => 427, 'name' => 'Samandağ Vergi Dairesi Müdürlüğü'],
            ['id' => 423, 'district_id' => 415, 'name' => 'Altınözü Malmüdürlüğü'],
            ['id' => 424, 'district_id' => 422, 'name' => 'Hassa Malmüdürlüğü'],
            ['id' => 425, 'district_id' => 429, 'name' => 'Yayladağı Malmüdürlüğü'],
            ['id' => 426, 'district_id' => 421, 'name' => 'Erzin Malmüdürlüğü'],
            ['id' => 427, 'district_id' => 418, 'name' => 'Belen Malmüdürlüğü'],
            ['id' => 428, 'district_id' => 425, 'name' => 'Kumlu Malmüdürlüğü'],
            ['id' => 429, 'district_id' => 440, 'name' => 'Davraz Vergi Dairesi Müdürlüğü'],
            ['id' => 430, 'district_id' => 440, 'name' => 'Kaymakkapı Vergi Dairesi Müdürlüğü'],
            ['id' => 431, 'district_id' => 436, 'name' => 'Eğirdir Vergi Dairesi Müdürlüğü'],
            ['id' => 432, 'district_id' => 445, 'name' => 'Yalvaç Vergi Dairesi Müdürlüğü'],
            ['id' => 433, 'district_id' => 435, 'name' => 'Atabey Malmüdürlüğü'],
            ['id' => 434, 'district_id' => 437, 'name' => 'Gelendost Malmüdürlüğü'],
            ['id' => 435, 'district_id' => 439, 'name' => 'Keçiborlu Malmüdürlüğü'],
            ['id' => 436, 'district_id' => 441, 'name' => 'Senirkent Malmüdürlüğü'],
            ['id' => 437, 'district_id' => 442, 'name' => 'Sütçüler Malmüdürlüğü'],
            ['id' => 438, 'district_id' => 443, 'name' => 'Şarkikaraağaç Malmüdürlüğü'],
            ['id' => 439, 'district_id' => 444, 'name' => 'Uluborlu Malmüdürlüğü'],
            ['id' => 440, 'district_id' => 434, 'name' => 'Aksu Malmüdürlüğü'],
            ['id' => 441, 'district_id' => 438, 'name' => 'Gönen Malmüdürlüğü'],
            ['id' => 442, 'district_id' => 446, 'name' => 'Yenişarbademli Malmüdürlüğü'],
            ['id' => 443, 'district_id' => 707, 'name' => 'İstiklâl Vergi Dairesi Müdürlüğü'],
            ['id' => 444, 'district_id' => 707, 'name' => 'Uray Vergi Dairesi Müdürlüğü'],
            ['id' => 445, 'district_id' => 707, 'name' => 'Liman Vergi Dairesi Müdürlüğü'],
            ['id' => 446, 'district_id' => 707, 'name' => 'Toros Vergi Dairesi Müdürlüğü'],
            ['id' => 447, 'district_id' => 707, 'name' => 'Mersin İhtisas Vergi Dairesi Müdürlüğü'],
            ['id' => 448, 'district_id' => 712, 'name' => 'Erdemli Vergi Dairesi Müdürlüğü'],
            ['id' => 449, 'district_id' => 716, 'name' => 'Silifke Vergi Dairesi Müdürlüğü'],
            ['id' => 450, 'district_id' => 708, 'name' => 'Anamur Vergi Dairesi Müdürlüğü'],
            ['id' => 451, 'district_id' => 717, 'name' => 'Kızılmurat Vergi Dairesi Müdürlüğü'],
            ['id' => 452, 'district_id' => 717, 'name' => 'Şehitkerim Vergi Dairesi Müdürlüğü'],
            ['id' => 453, 'district_id' => 713, 'name' => 'Gülnar Malmüdürlüğü'],
            ['id' => 454, 'district_id' => 715, 'name' => 'Mut Malmüdürlüğü'],
            ['id' => 455, 'district_id' => 709, 'name' => 'Aydıncık Malmüdürlüğü'],
            ['id' => 456, 'district_id' => 710, 'name' => 'Bozyazı Malmüdürlüğü'],
            ['id' => 457, 'district_id' => 717, 'name' => 'Çamlıyayla Malmüdürlüğü'],
            ['id' => 458, 'district_id' => 466, 'name' => 'Haliç İhtisas Vergi Dairesi Müdürlüğü'],
            ['id' => 459, 'district_id' => 466, 'name' => 'Vatan İhtisas Vergi Dairesi Müdürlüğü'],
            ['id' => 460, 'district_id' => 483, 'name' => 'Çamlıca İhtisas Vergi Dairesi Müdürlüğü'],
            ['id' => 461, 'district_id' => 483, 'name' => 'Alemdağ Vergi Dairesi Müdürlüğü'],
            ['id' => 462, 'district_id' => 466, 'name' => 'Yenikapı Vergi Dairesi Müdürlüğü'],
            ['id' => 463, 'district_id' => 499, 'name' => 'Büyük Mükellefler Vergi Dairesi Başkanlığı'],
            ['id' => 464, 'district_id' => 466, 'name' => 'Boğaziçi Kurumlar Vergi Dairesi Müdürlüğü'],
            ['id' => 465, 'district_id' => 466, 'name' => 'Marmara Kurumlar Vergi Dairesi Müdürlüğü'],
            ['id' => 466, 'district_id' => 466, 'name' => 'Davutpaşa Vergi Dairesi Müdürlüğü'],
            ['id' => 467, 'district_id' => 463, 'name' => 'Esenler Vergi Dairesi Müdürlüğü'],
            ['id' => 468, 'district_id' => 466, 'name' => 'Fatih Vergi Dairesi Müdürlüğü'],
            ['id' => 469, 'district_id' => 463, 'name' => 'Küçükköy Vergi Dairesi Müdürlüğü'],
            ['id' => 470, 'district_id' => 452, 'name' => 'Merter Vergi Dairesi Müdürlüğü'],
            ['id' => 471, 'district_id' => 471, 'name' => 'Sultanbeyli Vergi Dairesi Müdürlüğü'],
            ['id' => 472, 'district_id' => 449, 'name' => 'Anadolu Kurumlar Vergi Dairesi Müdürlüğü'],
            ['id' => 473, 'district_id' => 482, 'name' => 'Tuzla Vergi Dairesi Müdürlüğü'],
            ['id' => 474, 'district_id' => 449, 'name' => 'Kozyatağı Vergi Dairesi Müdürlüğü'],
            ['id' => 475, 'district_id' => 481, 'name' => 'Maslak Vergi Dairesi Müdürlüğü'],
            ['id' => 476, 'district_id' => 481, 'name' => 'Zincirlikuyu Vergi Dairesi Müdürlüğü'],
            ['id' => 477, 'district_id' => 454, 'name' => 'İkitelli Vergi Dairesi Müdürlüğü'],
            ['id' => 478, 'district_id' => 456, 'name' => 'Beşiktaş Vergi Dairesi Müdürlüğü'],
            ['id' => 479, 'district_id' => 483, 'name' => 'Ümraniye Vergi Dairesi Müdürlüğü'],
            ['id' => 480, 'district_id' => 466, 'name' => 'Yeditepe Veraset ve Harçlar Vergi Dairesi Müdürlüğü'],
            ['id' => 481, 'district_id' => 481, 'name' => 'Kasımpaşa Vergi Dairesi Müdürlüğü'],
            ['id' => 482, 'district_id' => 449, 'name' => 'Erenköy Vergi Dairesi Müdürlüğü'],
            ['id' => 483, 'district_id' => 466, 'name' => 'Hisar Veraset ve Harçlar Vergi Dairesi Müdürlüğü'],
            ['id' => 484, 'district_id' => 463, 'name' => 'Tuna Vergi Dairesi Müdürlüğü'],
            ['id' => 485, 'district_id' => 449, 'name' => 'Rıhtım Veraset ve Harçlar Vergi Dairesi Müdürlüğü'],
            ['id' => 486, 'district_id' => 463, 'name' => 'Güngören Vergi Dairesi Müdürlüğü'],
            ['id' => 487, 'district_id' => 452, 'name' => 'Kocasinan Vergi Dairesi Müdürlüğü'],
            ['id' => 488, 'district_id' => 452, 'name' => 'Güneşli Vergi Dairesi Müdürlüğü'],
            ['id' => 489, 'district_id' => 471, 'name' => 'Küçükyalı Vergi Dairesi Müdürlüğü'],
            ['id' => 490, 'district_id' => 474, 'name' => 'Pendik Vergi Dairesi Müdürlüğü'],
            ['id' => 491, 'district_id' => 455, 'name' => 'Bayrampaşa Vergi Dairesi Müdürlüğü'],
            ['id' => 492, 'district_id' => 466, 'name' => 'Beyazıt Vergi Dairesi Müdürlüğü'],
            ['id' => 493, 'district_id' => 459, 'name' => 'Beyoğlu Vergi Dairesi Müdürlüğü'],
            ['id' => 494, 'district_id' => 467, 'name' => 'Gaziosmanpaşa Vergi Dairesi Müdürlüğü'],
            ['id' => 495, 'district_id' => 469, 'name' => 'Göztepe Vergi Dairesi Müdürlüğü'],
            ['id' => 496, 'district_id' => 466, 'name' => 'Hocapaşa Vergi Dairesi Müdürlüğü'],
            ['id' => 497, 'district_id' => 469, 'name' => 'Kadıköy Vergi Dairesi Müdürlüğü'],
            ['id' => 498, 'district_id' => 466, 'name' => 'Kocamustafapaşa Vergi Dairesi Müdürlüğü'],
            ['id' => 499, 'district_id' => 481, 'name' => 'Mecidiyeköy Vergi Dairesi Müdürlüğü'],
            ['id' => 500, 'district_id' => 481, 'name' => 'Şişli Vergi Dairesi Müdürlüğü'],
            ['id' => 501, 'district_id' => 483, 'name' => 'Üsküdar Vergi Dairesi Müdürlüğü'],
            ['id' => 502, 'district_id' => 454, 'name' => 'Halkalı Vergi Dairesi Müdürlüğü'],
            ['id' => 503, 'district_id' => 481, 'name' => 'Kağıthane Vergi Dairesi Müdürlüğü'],
            ['id' => 504, 'district_id' => 466, 'name' => 'Zeytinburnu Vergi Dairesi Müdürlüğü'],
            ['id' => 505, 'district_id' => 483, 'name' => 'Beykoz Vergi Dairesi Müdürlüğü'],
            ['id' => 506, 'district_id' => 476, 'name' => 'Sarıyer Vergi Dairesi Müdürlüğü'],
            ['id' => 507, 'district_id' => 466, 'name' => 'Bakırköy Vergi Dairesi Müdürlüğü'],
            ['id' => 508, 'district_id' => 471, 'name' => 'Kartal Vergi Dairesi Müdürlüğü'],
            ['id' => 509, 'district_id' => 483, 'name' => 'Nakil Vasıtaları Vergi Dairesi Müdürlüğü'],
            ['id' => 510, 'district_id' => 483, 'name' => 'Sarıgazi Vergi Dairesi Müdürlüğü'],
            ['id' => 511, 'district_id' => 463, 'name' => 'Atışalanı Vergi Dairesi Müdürlüğü'],
            ['id' => 512, 'district_id' => 471, 'name' => 'Yakacık Vergi Dairesi Müdürlüğü'],
            ['id' => 513, 'district_id' => 452, 'name' => 'Yenibosna Vergi Dairesi Müdürlüğü'],
            ['id' => 514, 'district_id' => 450, 'name' => 'Avcılar Vergi Dairesi Müdürlüğü'],
            ['id' => 515, 'district_id' => 447, 'name' => 'Adalar Vergi Dairesi Müdürlüğü'],
            ['id' => 516, 'district_id' => 454, 'name' => 'Küçükçekmece Vergi Dairesi Müdürlüğü'],
            ['id' => 517, 'district_id' => 450, 'name' => 'Beylikdüzü Vergi Dairesi Müdürlüğü'],
            ['id' => 518, 'district_id' => 464, 'name' => 'Esenyurt Vergi Dairesi Müdürlüğü'],
            ['id' => 519, 'district_id' => 477, 'name' => 'Silivri Vergi Dairesi Müdürlüğü'],
            ['id' => 520, 'district_id' => 460, 'name' => 'Büyükçekmece Vergi Dairesi Müdürlüğü'],
            ['id' => 521, 'district_id' => 480, 'name' => 'Şile Vergi Dairesi Müdürlüğü'],
            ['id' => 522, 'district_id' => 500, 'name' => 'İzmir İhtisas Vergi Dairesi Müdürlüğü'],
            ['id' => 523, 'district_id' => 487, 'name' => '9 Eylül Vergi Dairesi Müdürlüğü'],
            ['id' => 524, 'district_id' => 502, 'name' => 'Yamanlar Vergi Dairesi Müdürlüğü'],
            ['id' => 525, 'district_id' => 492, 'name' => 'Belkahve Vergi Dairesi Müdürlüğü'],
            ['id' => 526, 'district_id' => 502, 'name' => 'Karşıyaka Vergi Dairesi Müdürlüğü'],
            ['id' => 527, 'district_id' => 506, 'name' => 'Kemeraltı Vergi Dairesi Müdürlüğü'],
            ['id' => 528, 'district_id' => 500, 'name' => 'Konak Vergi Dairesi Müdürlüğü'],
            ['id' => 529, 'district_id' => 506, 'name' => 'Kordon Vergi Dairesi Müdürlüğü'],
            ['id' => 530, 'district_id' => 493, 'name' => 'Şirinyer Vergi Dairesi Müdürlüğü'],
            ['id' => 531, 'district_id' => 493, 'name' => 'Kadifekale Vergi Dairesi Müdürlüğü'],
            ['id' => 532, 'district_id' => 493, 'name' => 'Taşıtlar Vergi Dairesi Müdürlüğü'],
            ['id' => 533, 'district_id' => 492, 'name' => 'Hasan Tahsin Vergi Dairesi Müdürlüğü'],
            ['id' => 534, 'district_id' => 492, 'name' => 'Bornova Vergi Dairesi Müdürlüğü'],
            ['id' => 535, 'district_id' => 506, 'name' => 'Çakabey Vergi Dairesi Müdürlüğü'],
            ['id' => 536, 'district_id' => 500, 'name' => 'Balçova Vergi Dairesi Müdürlüğü'],
            ['id' => 537, 'district_id' => 498, 'name' => 'Gaziemir Vergi Dairesi Müdürlüğü'],
            ['id' => 538, 'district_id' => 506, 'name' => 'Ege Vergi Dairesi Müdürlüğü'],
            ['id' => 539, 'district_id' => 502, 'name' => 'Çiğli Vergi Dairesi Müdürlüğü'],
            ['id' => 540, 'district_id' => 506, 'name' => 'Çakabey İhtisas Vergi Dairesi Müdürlüğü'],
            ['id' => 541, 'district_id' => 488, 'name' => 'Bayındır Vergi Dairesi Müdürlüğü'],
            ['id' => 542, 'district_id' => 490, 'name' => 'Bergama Vergi Dairesi Müdürlüğü'],
            ['id' => 543, 'district_id' => 508, 'name' => 'Menemen Vergi Dairesi Müdürlüğü'],
            ['id' => 544, 'district_id' => 510, 'name' => 'Ödemiş Vergi Dairesi Müdürlüğü'],
            ['id' => 545, 'district_id' => 513, 'name' => 'Tire Vergi Dairesi Müdürlüğü'],
            ['id' => 546, 'district_id' => 514, 'name' => 'Torbalı Vergi Dairesi Müdürlüğü'],
            ['id' => 547, 'district_id' => 503, 'name' => 'Kemalpaşa Vergi Dairesi Müdürlüğü'],
            ['id' => 548, 'district_id' => 515, 'name' => 'Urla Vergi Dairesi Müdürlüğü'],
            ['id' => 549, 'district_id' => 512, 'name' => 'Selçuk Vergi Dairesi Müdürlüğü'],
            ['id' => 550, 'district_id' => 504, 'name' => 'Kınık Vergi Dairesi Müdürlüğü'],
            ['id' => 551, 'district_id' => 505, 'name' => 'Kiraz Vergi Dairesi Müdürlüğü'],
            ['id' => 552, 'district_id' => 494, 'name' => 'Çeşme Vergi Dairesi Müdürlüğü'],
            ['id' => 553, 'district_id' => 486, 'name' => 'Aliağa Vergi Dairesi Müdürlüğü'],
            ['id' => 554, 'district_id' => 507, 'name' => 'Menderes Vergi Dairesi Müdürlüğü'],
            ['id' => 555, 'district_id' => 496, 'name' => 'Dikili Malmüdürlüğü'],
            ['id' => 556, 'district_id' => 497, 'name' => 'Foça Malmüdürlüğü'],
            ['id' => 557, 'district_id' => 501, 'name' => 'Karaburun Malmüdürlüğü'],
            ['id' => 558, 'district_id' => 511, 'name' => 'Seferihisar Malmüdürlüğü'],
            ['id' => 559, 'district_id' => 491, 'name' => 'Beydağ Malmüdürlüğü'],
            ['id' => 560, 'district_id' => 543, 'name' => 'Kars Vergi Dairesi Müdürlüğü'],
            ['id' => 561, 'district_id' => 540, 'name' => 'Arpaçay Malmüdürlüğü'],
            ['id' => 562, 'district_id' => 541, 'name' => 'Digor Malmüdürlüğü'],
            ['id' => 563, 'district_id' => 542, 'name' => 'Kağızman Malmüdürlüğü'],
            ['id' => 564, 'district_id' => 544, 'name' => 'Sarıkamış Malmüdürlüğü'],
            ['id' => 565, 'district_id' => 545, 'name' => 'Selim Malmüdürlüğü'],
            ['id' => 566, 'district_id' => 546, 'name' => 'Susuz Malmüdürlüğü'],
            ['id' => 567, 'district_id' => 539, 'name' => 'Akyaka Malmüdürlüğü'],
            ['id' => 568, 'district_id' => 561, 'name' => 'Kastamonu Vergi Dairesi Müdürlüğü'],
            ['id' => 569, 'district_id' => 566, 'name' => 'Tosya Vergi Dairesi Müdürlüğü'],
            ['id' => 570, 'district_id' => 565, 'name' => 'Taşköprü Vergi Dairesi Müdürlüğü'],
            ['id' => 571, 'district_id' => 549, 'name' => 'Araç Malmüdürlüğü'],
            ['id' => 572, 'district_id' => 550, 'name' => 'Azdavay Malmüdürlüğü'],
            ['id' => 573, 'district_id' => 551, 'name' => 'Bozkurt Malmüdürlüğü'],
            ['id' => 574, 'district_id' => 552, 'name' => 'Cide Malmüdürlüğü'],
            ['id' => 575, 'district_id' => 553, 'name' => 'Çatalzeytin Malmüdürlüğü'],
            ['id' => 576, 'district_id' => 554, 'name' => 'Daday Malmüdürlüğü'],
            ['id' => 577, 'district_id' => 555, 'name' => 'Devrekani Malmüdürlüğü'],
            ['id' => 578, 'district_id' => 559, 'name' => 'İnebolu Malmüdürlüğü'],
            ['id' => 579, 'district_id' => 560, 'name' => 'Küre Malmüdürlüğü'],
            ['id' => 580, 'district_id' => 547, 'name' => 'Abana Malmüdürlüğü'],
            ['id' => 581, 'district_id' => 558, 'name' => 'İhsangazi Malmüdürlüğü'],
            ['id' => 582, 'district_id' => 562, 'name' => 'Pınarbaşı Malmüdürlüğü'],
            ['id' => 583, 'district_id' => 564, 'name' => 'Şenpazar Malmüdürlüğü'],
            ['id' => 584, 'district_id' => 548, 'name' => 'Ağlı Malmüdürlüğü'],
            ['id' => 585, 'district_id' => 556, 'name' => 'Doğanyurt Malmüdürlüğü'],
            ['id' => 586, 'district_id' => 557, 'name' => 'Hanönü Malmüdürlüğü'],
            ['id' => 587, 'district_id' => 563, 'name' => 'Seydiler Malmüdürlüğü'],
            ['id' => 588, 'district_id' => 573, 'name' => 'Kayseri İhtisas Vergi Dairesi Müdürlüğü'],
            ['id' => 589, 'district_id' => 573, 'name' => 'Mimar Sinan Vergi Dairesi Müdürlüğü'],
            ['id' => 590, 'district_id' => 573, 'name' => 'Erciyes Vergi Dairesi Müdürlüğü'],
            ['id' => 591, 'district_id' => 573, 'name' => 'Kaleönü Vergi Dairesi Müdürlüğü'],
            ['id' => 592, 'district_id' => 573, 'name' => 'Gevher Nesibe Vergi Dairesi Müdürlüğü'],
            ['id' => 593, 'district_id' => 569, 'name' => 'Develi Vergi Dairesi Müdürlüğü'],
            ['id' => 594, 'district_id' => 576, 'name' => 'Pınarbaşı Vergi Dairesi Müdürlüğü'],
            ['id' => 595, 'district_id' => 568, 'name' => 'Bünyan Vergi Dairesi Müdürlüğü'],
            ['id' => 596, 'district_id' => 570, 'name' => 'Felahiye Malmüdürlüğü'],
            ['id' => 597, 'district_id' => 572, 'name' => 'İncesu Malmüdürlüğü'],
            ['id' => 598, 'district_id' => 577, 'name' => 'Sarıoğlan Malmüdürlüğü'],
            ['id' => 599, 'district_id' => 578, 'name' => 'Sarız Malmüdürlüğü'],
            ['id' => 600, 'district_id' => 580, 'name' => 'Tomarza Malmüdürlüğü'],
            ['id' => 601, 'district_id' => 581, 'name' => 'Yahyalı Malmüdürlüğü'],
            ['id' => 602, 'district_id' => 582, 'name' => 'Yeşilhisar Malmüdürlüğü'],
            ['id' => 603, 'district_id' => 567, 'name' => 'Akkışla Malmüdürlüğü'],
            ['id' => 604, 'district_id' => 571, 'name' => 'Hacılar Malmüdürlüğü'],
            ['id' => 605, 'district_id' => 575, 'name' => 'Özvatan Malmüdürlüğü'],
            ['id' => 606, 'district_id' => 596, 'name' => 'Kırklareli Vergi Dairesi Müdürlüğü'],
            ['id' => 607, 'district_id' => 595, 'name' => 'Lüleburgaz Vergi Dairesi Müdürlüğü'],
            ['id' => 608, 'district_id' => 592, 'name' => 'Babaeski Vergi Dairesi Müdürlüğü'],
            ['id' => 609, 'district_id' => 593, 'name' => 'Demirköy Malmüdürlüğü'],
            ['id' => 610, 'district_id' => 594, 'name' => 'Kofçaz Malmüdürlüğü'],
            ['id' => 611, 'district_id' => 597, 'name' => 'Pehlivanköy Malmüdürlüğü'],
            ['id' => 612, 'district_id' => 598, 'name' => 'Pınarhisar Malmüdürlüğü'],
            ['id' => 613, 'district_id' => 599, 'name' => 'Vize Malmüdürlüğü'],
            ['id' => 614, 'district_id' => 605, 'name' => 'Kırşehir Vergi Dairesi Müdürlüğü'],
            ['id' => 615, 'district_id' => 604, 'name' => 'Kaman Vergi Dairesi Müdürlüğü'],
            ['id' => 616, 'district_id' => 603, 'name' => 'Çiçekdağı Malmüdürlüğü'],
            ['id' => 617, 'district_id' => 606, 'name' => 'Mucur Malmüdürlüğü'],
            ['id' => 618, 'district_id' => 601, 'name' => 'Akpınar Malmüdürlüğü'],
            ['id' => 619, 'district_id' => 600, 'name' => 'Akçakent Malmüdürlüğü'],
            ['id' => 620, 'district_id' => 602, 'name' => 'Boztepe Malmüdürlüğü'],
            ['id' => 621, 'district_id' => 618, 'name' => 'Kocaeli İhtisas Vergi Dairesi Müdürlüğü'],
            ['id' => 622, 'district_id' => 618, 'name' => 'Tepecik Vergi Dairesi Müdürlüğü'],
            ['id' => 623, 'district_id' => 618, 'name' => 'Alemdar Vergi Dairesi Müdürlüğü'],
            ['id' => 624, 'district_id' => 616, 'name' => 'Gebze İhtisas Vergi Dairesi Müdürlüğü'],
            ['id' => 625, 'district_id' => 618, 'name' => 'Acısu Vergi Dairesi Müdürlüğü'],
            ['id' => 626, 'district_id' => 616, 'name' => 'Uluçınar Vergi Dairesi Müdürlüğü'],
            ['id' => 627, 'district_id' => 616, 'name' => 'İlyasbey Vergi Dairesi Müdürlüğü'],
            ['id' => 628, 'district_id' => 617, 'name' => 'Gölcük Vergi Dairesi Müdürlüğü'],
            ['id' => 629, 'district_id' => 620, 'name' => 'Karamürsel Vergi Dairesi Müdürlüğü'],
            ['id' => 630, 'district_id' => 622, 'name' => 'Körfez Vergi Dairesi Müdürlüğü'],
            ['id' => 631, 'district_id' => 614, 'name' => 'Derince Vergi Dairesi Müdürlüğü'],
            ['id' => 632, 'district_id' => 619, 'name' => 'Kandıra Malmüdürlüğü'],
            ['id' => 633, 'district_id' => 648, 'name' => 'Konya İhtisas Vergi Dairesi Müdürlüğü'],
            ['id' => 634, 'district_id' => 648, 'name' => 'Selçuk Vergi Dairesi Müdürlüğü'],
            ['id' => 635, 'district_id' => 648, 'name' => 'Mevlana Vergi Dairesi Müdürlüğü'],
            ['id' => 636, 'district_id' => 648, 'name' => 'Meram Vergi Dairesi Müdürlüğü'],
            ['id' => 637, 'district_id' => 648, 'name' => 'Alaaddin Vergi Dairesi Müdürlüğü'],
            ['id' => 638, 'district_id' => 625, 'name' => 'Akşehir Vergi Dairesi Müdürlüğü'],
            ['id' => 639, 'district_id' => 636, 'name' => 'Ereğli Vergi Dairesi Müdürlüğü'],
            ['id' => 640, 'district_id' => 627, 'name' => 'Beyşehir Vergi Dairesi Müdürlüğü'],
            ['id' => 641, 'district_id' => 629, 'name' => 'Cihanbeyli Vergi Dairesi Müdürlüğü'],
            ['id' => 642, 'district_id' => 631, 'name' => 'Çumra Vergi Dairesi Müdürlüğü'],
            ['id' => 643, 'district_id' => 649, 'name' => 'Seydişehir Vergi Dairesi Müdürlüğü'],
            ['id' => 644, 'district_id' => 641, 'name' => 'Ilgın Vergi Dairesi Müdürlüğü'],
            ['id' => 645, 'district_id' => 645, 'name' => 'Kulu Vergi Dairesi Müdürlüğü'],
            ['id' => 646, 'district_id' => 643, 'name' => 'Karapınar Vergi Dairesi Müdürlüğü'],
            ['id' => 647, 'district_id' => 628, 'name' => 'Bozkır Malmüdürlüğü'],
            ['id' => 648, 'district_id' => 634, 'name' => 'Doğanhisar Malmüdürlüğü'],
            ['id' => 649, 'district_id' => 638, 'name' => 'Hadim Malmüdürlüğü'],
            ['id' => 650, 'district_id' => 642, 'name' => 'Kadınhanı Malmüdürlüğü'],
            ['id' => 651, 'district_id' => 647, 'name' => 'Sarayönü Malmüdürlüğü'],
            ['id' => 652, 'district_id' => 653, 'name' => 'Yunak Malmüdürlüğü'],
            ['id' => 653, 'district_id' => 624, 'name' => 'Akören Malmüdürlüğü'],
            ['id' => 654, 'district_id' => 626, 'name' => 'Altınekin Malmüdürlüğü'],
            ['id' => 655, 'district_id' => 633, 'name' => 'Derebucak Malmüdürlüğü'],
            ['id' => 656, 'district_id' => 640, 'name' => 'Hüyük Malmüdürlüğü'],
            ['id' => 657, 'district_id' => 650, 'name' => 'Taşkent Malmüdürlüğü'],
            ['id' => 658, 'district_id' => 623, 'name' => 'Ahırlı Malmüdürlüğü'],
            ['id' => 659, 'district_id' => 630, 'name' => 'Çeltik Malmüdürlüğü'],
            ['id' => 660, 'district_id' => 632, 'name' => 'Derbent Malmüdürlüğü'],
            ['id' => 661, 'district_id' => 635, 'name' => 'Emirgazi Malmüdürlüğü'],
            ['id' => 662, 'district_id' => 637, 'name' => 'Güneysınır Malmüdürlüğü'],
            ['id' => 663, 'district_id' => 639, 'name' => 'Halkapınar Malmüdürlüğü'],
            ['id' => 664, 'district_id' => 651, 'name' => 'Tuzlukçu Malmüdürlüğü'],
            ['id' => 665, 'district_id' => 652, 'name' => 'Yalıhüyük Malmüdürlüğü'],
            ['id' => 666, 'district_id' => 662, 'name' => '30 Ağustos Vergi Dairesi Müdürlüğü'],
            ['id' => 667, 'district_id' => 662, 'name' => 'Çinili Vergi Dairesi Müdürlüğü'],
            ['id' => 668, 'district_id' => 660, 'name' => 'Gediz Vergi Dairesi Müdürlüğü'],
            ['id' => 669, 'district_id' => 664, 'name' => 'Simav Vergi Dairesi Müdürlüğü'],
            ['id' => 670, 'district_id' => 666, 'name' => 'Tavşanlı Vergi Dairesi Müdürlüğü'],
            ['id' => 671, 'district_id' => 659, 'name' => 'Emet Vergi Dairesi Müdürlüğü'],
            ['id' => 672, 'district_id' => 654, 'name' => 'Altıntaş Malmüdürlüğü'],
            ['id' => 673, 'district_id' => 657, 'name' => 'Domaniç Malmüdürlüğü'],
            ['id' => 674, 'district_id' => 655, 'name' => 'Aslanapa Malmüdürlüğü'],
            ['id' => 675, 'district_id' => 658, 'name' => 'Dumlupınar Malmüdürlüğü'],
            ['id' => 676, 'district_id' => 661, 'name' => 'Hisarcık Malmüdürlüğü'],
            ['id' => 677, 'district_id' => 655, 'name' => 'Şaphane Malmüdürlüğü'],
            ['id' => 678, 'district_id' => 656, 'name' => 'Çavdarhisar Malmüdürlüğü'],
            ['id' => 679, 'district_id' => 663, 'name' => 'Pazarlar Malmüdürlüğü'],
            ['id' => 680, 'district_id' => 670, 'name' => 'Fırat Vergi Dairesi Müdürlüğü'],
            ['id' => 681, 'district_id' => 670, 'name' => 'Beydağı Vergi Dairesi Müdürlüğü'],
            ['id' => 682, 'district_id' => 667, 'name' => 'Akçadağ Malmüdürlüğü'],
            ['id' => 683, 'district_id' => 668, 'name' => 'Arapgir Malmüdürlüğü'],
            ['id' => 684, 'district_id' => 669, 'name' => 'Arguvan Malmüdürlüğü'],
            ['id' => 685, 'district_id' => 671, 'name' => 'Darende Malmüdürlüğü'],
            ['id' => 686, 'district_id' => 672, 'name' => 'Doğanşehir Malmüdürlüğü'],
            ['id' => 687, 'district_id' => 674, 'name' => 'Hekimhan Malmüdürlüğü'],
            ['id' => 688, 'district_id' => 677, 'name' => 'Pütürge Malmüdürlüğü'],
            ['id' => 689, 'district_id' => 679, 'name' => 'Yeşilyurt Malmüdürlüğü'],
            ['id' => 690, 'district_id' => 670, 'name' => 'Battalgazi Malmüdürlüğü'],
            ['id' => 691, 'district_id' => 673, 'name' => 'Doğanyol Malmüdürlüğü'],
            ['id' => 692, 'district_id' => 675, 'name' => 'Kale Malmüdürlüğü'],
            ['id' => 693, 'district_id' => 676, 'name' => 'Kuluncak Malmüdürlüğü'],
            ['id' => 694, 'district_id' => 678, 'name' => 'Yazıhan Malmüdürlüğü'],
            ['id' => 695, 'district_id' => 696, 'name' => 'Manisa İhtisas Vergi Dairesi Müdürlüğü'],
            ['id' => 696, 'district_id' => 696, 'name' => 'Alaybey Vergi Dairesi Müdürlüğü'],
            ['id' => 697, 'district_id' => 696, 'name' => 'Mesir Vergi Dairesi Müdürlüğü'],
            ['id' => 698, 'district_id' => 681, 'name' => 'Akhisar Vergi Dairesi Müdürlüğü'],
            ['id' => 699, 'district_id' => 682, 'name' => 'Alaşehir Vergi Dairesi Müdürlüğü'],
            ['id' => 700, 'district_id' => 683, 'name' => 'Demirci Vergi Dairesi Müdürlüğü'],
            ['id' => 701, 'district_id' => 686, 'name' => 'Kırkağaç Vergi Dairesi Müdürlüğü'],
            ['id' => 702, 'district_id' => 689, 'name' => 'Salihli Adil Oral Vergi Dairesi Müdürlüğü'],
            ['id' => 703, 'district_id' => 690, 'name' => 'Sarıgöl Vergi Dairesi Müdürlüğü'],
            ['id' => 704, 'district_id' => 691, 'name' => 'Saruhanlı Vergi Dairesi Müdürlüğü'],
            ['id' => 705, 'district_id' => 693, 'name' => 'Soma Vergi Dairesi Müdürlüğü'],
            ['id' => 706, 'district_id' => 695, 'name' => 'Turgutlu Vergi Dairesi Müdürlüğü'],
            ['id' => 707, 'district_id' => 685, 'name' => 'Gördes Vergi Dairesi Müdürlüğü'],
            ['id' => 708, 'district_id' => 688, 'name' => 'Kula Vergi Dairesi Müdürlüğü'],
            ['id' => 709, 'district_id' => 692, 'name' => 'Selendi Malmüdürlüğü'],
            ['id' => 710, 'district_id' => 680, 'name' => 'Ahmetli Malmüdürlüğü'],
            ['id' => 711, 'district_id' => 684, 'name' => 'Gölmarmara Malmüdürlüğü'],
            ['id' => 712, 'district_id' => 687, 'name' => 'Köprübaşı Malmüdürlüğü'],
            ['id' => 713, 'district_id' => 519, 'name' => 'Aslanbey Vergi Dairesi Müdürlüğü'],
            ['id' => 714, 'district_id' => 519, 'name' => 'Aksu Vergi Dairesi Müdürlüğü'],
            ['id' => 715, 'district_id' => 521, 'name' => 'Elbistan Vergi Dairesi Müdürlüğü'],
            ['id' => 716, 'district_id' => 516, 'name' => 'Afşin Vergi Dairesi Müdürlüğü'],
            ['id' => 717, 'district_id' => 525, 'name' => 'Pazarcık Vergi Dairesi Müdürlüğü'],
            ['id' => 718, 'district_id' => 517, 'name' => 'Andırın Malmüdürlüğü'],
            ['id' => 719, 'district_id' => 522, 'name' => 'Göksun Malmüdürlüğü'],
            ['id' => 720, 'district_id' => 526, 'name' => 'Türkoğlu Malmüdürlüğü'],
            ['id' => 721, 'district_id' => 518, 'name' => 'Çağlayancerit Malmüdürlüğü'],
            ['id' => 722, 'district_id' => 520, 'name' => 'Ekinözü Malmüdürlüğü'],
            ['id' => 723, 'district_id' => 523, 'name' => 'Nurhak Malmüdürlüğü'],
            ['id' => 724, 'district_id' => 697, 'name' => 'Mardin Vergi Dairesi Müdürlüğü'],
            ['id' => 725, 'district_id' => 700, 'name' => 'Kızıltepe Vergi Dairesi Müdürlüğü'],
            ['id' => 726, 'district_id' => 703, 'name' => 'Nusaybin Vergi Dairesi Müdürlüğü'],
            ['id' => 727, 'district_id' => 699, 'name' => 'Derik Malmüdürlüğü'],
            ['id' => 728, 'district_id' => 701, 'name' => 'Mazıdağı Malmüdürlüğü'],
            ['id' => 729, 'district_id' => 702, 'name' => 'Midyat Malmüdürlüğü'],
            ['id' => 730, 'district_id' => 704, 'name' => 'Ömerli Malmüdürlüğü'],
            ['id' => 731, 'district_id' => 705, 'name' => 'Savur Malmüdürlüğü'],
            ['id' => 732, 'district_id' => 698, 'name' => 'Dargeçit Malmüdürlüğü'],
            ['id' => 733, 'district_id' => 706, 'name' => 'Yeşilli Malmüdürlüğü'],
            ['id' => 734, 'district_id' => 727, 'name' => 'Muğla Vergi Dairesi Müdürlüğü'],
            ['id' => 735, 'district_id' => 720, 'name' => 'Bodrum Vergi Dairesi Müdürlüğü'],
            ['id' => 736, 'district_id' => 723, 'name' => 'Fethiye Vergi Dairesi Müdürlüğü'],
            ['id' => 737, 'district_id' => 725, 'name' => 'Köyceğiz Vergi Dairesi Müdürlüğü'],
            ['id' => 738, 'district_id' => 728, 'name' => 'Milas Vergi Dairesi Müdürlüğü'],
            ['id' => 739, 'district_id' => 726, 'name' => 'Marmaris Vergi Dairesi Müdürlüğü'],
            ['id' => 740, 'district_id' => 732, 'name' => 'Yatağan Vergi Dairesi Müdürlüğü'],
            ['id' => 741, 'district_id' => 722, 'name' => 'Datça Malmüdürlüğü'],
            ['id' => 742, 'district_id' => 731, 'name' => 'Ula Malmüdürlüğü'],
            ['id' => 743, 'district_id' => 721, 'name' => 'Dalaman Malmüdürlüğü'],
            ['id' => 744, 'district_id' => 729, 'name' => 'Ortaca Malmüdürlüğü'],
            ['id' => 745, 'district_id' => 724, 'name' => 'Kavaklıdere Malmüdürlüğü'],
            ['id' => 746, 'district_id' => 730, 'name' => 'Seydikemer Malmüdürlüğü'],
            ['id' => 747, 'district_id' => 737, 'name' => 'Muş Vergi Dairesi Müdürlüğü'],
            ['id' => 748, 'district_id' => 733, 'name' => 'Bulanık Malmüdürlüğü'],
            ['id' => 749, 'district_id' => 736, 'name' => 'Malazgirt Malmüdürlüğü'],
            ['id' => 750, 'district_id' => 738, 'name' => 'Varto Malmüdürlüğü'],
            ['id' => 751, 'district_id' => 734, 'name' => 'Hasköy Malmüdürlüğü'],
            ['id' => 752, 'district_id' => 735, 'name' => 'Korkut Malmüdürlüğü'],
            ['id' => 753, 'district_id' => 745, 'name' => 'Nevşehir Vergi Dairesi Müdürlüğü'],
            ['id' => 754, 'district_id' => 740, 'name' => 'Avanos Malmüdürlüğü'],
            ['id' => 755, 'district_id' => 741, 'name' => 'Derinkuyu Malmüdürlüğü'],
            ['id' => 756, 'district_id' => 742, 'name' => 'Gülşehir Malmüdürlüğü'],
            ['id' => 757, 'district_id' => 743, 'name' => 'Hacıbektaş Malmüdürlüğü'],
            ['id' => 758, 'district_id' => 744, 'name' => 'Kozaklı Malmüdürlüğü'],
            ['id' => 759, 'district_id' => 746, 'name' => 'Ürgüp Malmüdürlüğü'],
            ['id' => 760, 'district_id' => 739, 'name' => 'Acıgöl Malmüdürlüğü'],
            ['id' => 761, 'district_id' => 751, 'name' => 'Niğde Vergi Dairesi Müdürlüğü'],
            ['id' => 762, 'district_id' => 748, 'name' => 'Bor Vergi Dairesi Müdürlüğü'],
            ['id' => 763, 'district_id' => 749, 'name' => 'Çamardı Malmüdürlüğü'],
            ['id' => 764, 'district_id' => 752, 'name' => 'Ulukışla Malmüdürlüğü'],
            ['id' => 765, 'district_id' => 747, 'name' => 'Altunhisar Malmüdürlüğü'],
            ['id' => 766, 'district_id' => 750, 'name' => 'Çiftlik Malmüdürlüğü'],
            ['id' => 767, 'district_id' => 754, 'name' => 'Boztepe Vergi Dairesi Müdürlüğü'],
            ['id' => 768, 'district_id' => 754, 'name' => 'Köprübaşı Vergi Dairesi Müdürlüğü'],
            ['id' => 769, 'district_id' => 759, 'name' => 'Fatsa Vergi Dairesi Müdürlüğü'],
            ['id' => 770, 'district_id' => 771, 'name' => 'Ünye Vergi Dairesi Müdürlüğü'],
            ['id' => 771, 'district_id' => 753, 'name' => 'Akkuş Malmüdürlüğü'],
            ['id' => 772, 'district_id' => 755, 'name' => 'Aybastı Malmüdürlüğü'],
            ['id' => 773, 'district_id' => 760, 'name' => 'Gölköy Malmüdürlüğü'],
            ['id' => 774, 'district_id' => 766, 'name' => 'Korgan Malmüdürlüğü'],
            ['id' => 775, 'district_id' => 767, 'name' => 'Kumru Malmüdürlüğü'],
            ['id' => 776, 'district_id' => 768, 'name' => 'Mesudiye Malmüdürlüğü'],
            ['id' => 777, 'district_id' => 769, 'name' => 'Perşembe Malmüdürlüğü'],
            ['id' => 778, 'district_id' => 770, 'name' => 'Ulubey Malmüdürlüğü'],
            ['id' => 779, 'district_id' => 761, 'name' => 'Gülyalı Malmüdürlüğü'],
            ['id' => 780, 'district_id' => 762, 'name' => 'Gürgentepe Malmüdürlüğü'],
            ['id' => 781, 'district_id' => 756, 'name' => 'Çamaş Malmüdürlüğü'],
            ['id' => 782, 'district_id' => 757, 'name' => 'Çatalpınar Malmüdürlüğü'],
            ['id' => 783, 'district_id' => 758, 'name' => 'Çaybaşı Malmüdürlüğü'],
            ['id' => 784, 'district_id' => 763, 'name' => 'İkizce Malmüdürlüğü'],
            ['id' => 785, 'district_id' => 764, 'name' => 'Kabadüz Malmüdürlüğü'],
            ['id' => 786, 'district_id' => 765, 'name' => 'Kabataş Malmüdürlüğü'],
            ['id' => 787, 'district_id' => 789, 'name' => 'Kaçkar Vergi Dairesi Müdürlüğü'],
            ['id' => 788, 'district_id' => 789, 'name' => 'Yeşilçay Vergi Dairesi Müdürlüğü'],
            ['id' => 789, 'district_id' => 781, 'name' => 'Çayeli Vergi Dairesi Müdürlüğü'],
            ['id' => 790, 'district_id' => 790, 'name' => 'Pazar Vergi Dairesi Müdürlüğü'],
            ['id' => 791, 'district_id' => 779, 'name' => 'Ardeşen Vergi Dairesi Müdürlüğü'],
            ['id' => 792, 'district_id' => 780, 'name' => 'Çamlıhemşin Malmüdürlüğü'],
            ['id' => 793, 'district_id' => 783, 'name' => 'Fındıklı Malmüdürlüğü'],
            ['id' => 794, 'district_id' => 786, 'name' => 'İkizdere Malmüdürlüğü'],
            ['id' => 795, 'district_id' => 788, 'name' => 'Kalkandere Malmüdürlüğü'],
            ['id' => 796, 'district_id' => 784, 'name' => 'Güneysu Malmüdürlüğü'],
            ['id' => 797, 'district_id' => 782, 'name' => 'Derepazarı Malmüdürlüğü'],
            ['id' => 798, 'district_id' => 785, 'name' => 'Hemşin Malmüdürlüğü'],
            ['id' => 799, 'district_id' => 787, 'name' => 'İyidere Malmüdürlüğü'],
            ['id' => 800, 'district_id' => 804, 'name' => 'Gümrükönü Vergi Dairesi Müdürlüğü'],
            ['id' => 801, 'district_id' => 791, 'name' => 'Ali Fuat Cebesoy Vergi Dairesi Müdürlüğü'],
            ['id' => 802, 'district_id' => 803, 'name' => 'Sapanca Vergi Dairesi Müdürlüğü'],
            ['id' => 803, 'district_id' => 792, 'name' => 'Akyazı Vergi Dairesi Müdürlüğü'],
            ['id' => 804, 'district_id' => 796, 'name' => 'Geyve Vergi Dairesi Müdürlüğü'],
            ['id' => 805, 'district_id' => 797, 'name' => 'Hendek Vergi Dairesi Müdürlüğü'],
            ['id' => 806, 'district_id' => 799, 'name' => 'Karasu Vergi Dairesi Müdürlüğü'],
            ['id' => 807, 'district_id' => 800, 'name' => 'Kaynarca Malmüdürlüğü'],
            ['id' => 808, 'district_id' => 801, 'name' => 'Kocaali Malmüdürlüğü'],
            ['id' => 809, 'district_id' => 802, 'name' => 'Pamukova Malmüdürlüğü'],
            ['id' => 810, 'district_id' => 806, 'name' => 'Taraklı Malmüdürlüğü'],
            ['id' => 811, 'district_id' => 798, 'name' => 'Karapürçek Malmüdürlüğü'],
            ['id' => 812, 'district_id' => 816, 'name' => '19 Mayıs Vergi Dairesi Müdürlüğü'],
            ['id' => 813, 'district_id' => 816, 'name' => 'Gaziler Vergi Dairesi Müdürlüğü'],
            ['id' => 814, 'district_id' => 816, 'name' => 'Zafer Vergi Dairesi Müdürlüğü'],
            ['id' => 815, 'district_id' => 812, 'name' => 'Bafra Vergi Dairesi Müdürlüğü'],
            ['id' => 816, 'district_id' => 814, 'name' => 'Çarşamba Vergi Dairesi Müdürlüğü'],
            ['id' => 817, 'district_id' => 821, 'name' => 'Terme Vergi Dairesi Müdürlüğü'],
            ['id' => 818, 'district_id' => 815, 'name' => 'Havza Vergi Dairesi Müdürlüğü'],
            ['id' => 819, 'district_id' => 808, 'name' => 'Alaçam Malmüdürlüğü'],
            ['id' => 820, 'district_id' => 817, 'name' => 'Kavak Malmüdürlüğü'],
            ['id' => 821, 'district_id' => 818, 'name' => 'Ladik Malmüdürlüğü'],
            ['id' => 822, 'district_id' => 822, 'name' => 'Vezirköprü Malmüdürlüğü'],
            ['id' => 823, 'district_id' => 809, 'name' => 'Asarcık Malmüdürlüğü'],
            ['id' => 824, 'district_id' => 807, 'name' => 'Ondokuz Mayıs Malmüdürlüğü'],
            ['id' => 825, 'district_id' => 819, 'name' => 'Salıpazarı Malmüdürlüğü'],
            ['id' => 826, 'district_id' => 820, 'name' => 'Tekkeköy Malmüdürlüğü'],
            ['id' => 827, 'district_id' => 811, 'name' => 'Ayvacık Malmüdürlüğü'],
            ['id' => 828, 'district_id' => 823, 'name' => 'Yakakent Malmüdürlüğü'],
            ['id' => 829, 'district_id' => 827, 'name' => 'Siirt Vergi Dairesi Müdürlüğü'],
            ['id' => 830, 'district_id' => 824, 'name' => 'Baykan Malmüdürlüğü'],
            ['id' => 831, 'district_id' => 825, 'name' => 'Eruh Malmüdürlüğü'],
            ['id' => 832, 'district_id' => 826, 'name' => 'Kurtalan Malmüdürlüğü'],
            ['id' => 833, 'district_id' => 828, 'name' => 'Pervari Malmüdürlüğü'],
            ['id' => 834, 'district_id' => 829, 'name' => 'Şirvan Malmüdürlüğü'],
            ['id' => 835, 'district_id' => 837, 'name' => 'Sinop Vergi Dairesi Müdürlüğü'],
            ['id' => 836, 'district_id' => 832, 'name' => 'Boyabat Vergi Dairesi Müdürlüğü'],
            ['id' => 837, 'district_id' => 831, 'name' => 'Ayancık Malmüdürlüğü'],
            ['id' => 838, 'district_id' => 834, 'name' => 'Durağan Malmüdürlüğü'],
            ['id' => 839, 'district_id' => 835, 'name' => 'Erfelek Malmüdürlüğü'],
            ['id' => 840, 'district_id' => 836, 'name' => 'Gerze Malmüdürlüğü'],
            ['id' => 841, 'district_id' => 839, 'name' => 'Türkeli Malmüdürlüğü'],
            ['id' => 842, 'district_id' => 833, 'name' => 'Dikmen Malmüdürlüğü'],
            ['id' => 843, 'district_id' => 838, 'name' => 'Saraydüzü Malmüdürlüğü'],
            ['id' => 844, 'district_id' => 851, 'name' => 'Kale Vergi Dairesi Müdürlüğü'],
            ['id' => 845, 'district_id' => 851, 'name' => 'Site Vergi Dairesi Müdürlüğü'],
            ['id' => 846, 'district_id' => 853, 'name' => 'Şarkışla Vergi Dairesi Müdürlüğü'],
            ['id' => 847, 'district_id' => 842, 'name' => 'Divriği Malmüdürlüğü'],
            ['id' => 848, 'district_id' => 844, 'name' => 'Gemerek Malmüdürlüğü'],
            ['id' => 849, 'district_id' => 846, 'name' => 'Gürün Malmüdürlüğü'],
            ['id' => 850, 'district_id' => 847, 'name' => 'Hafik Malmüdürlüğü'],
            ['id' => 851, 'district_id' => 848, 'name' => 'İmranlı Malmüdürlüğü'],
            ['id' => 852, 'district_id' => 849, 'name' => 'Kangal Malmüdürlüğü'],
            ['id' => 853, 'district_id' => 850, 'name' => 'Koyulhisar Malmüdürlüğü'],
            ['id' => 854, 'district_id' => 852, 'name' => 'Suşehri Malmüdürlüğü'],
            ['id' => 855, 'district_id' => 855, 'name' => 'Yıldızeli Malmüdürlüğü'],
            ['id' => 856, 'district_id' => 856, 'name' => 'Zara Malmüdürlüğü'],
            ['id' => 857, 'district_id' => 840, 'name' => 'Akıncılar Malmüdürlüğü'],
            ['id' => 858, 'district_id' => 841, 'name' => 'Altınyayla Malmüdürlüğü'],
            ['id' => 859, 'district_id' => 843, 'name' => 'Doğanşar Malmüdürlüğü'],
            ['id' => 860, 'district_id' => 845, 'name' => 'Gölova Malmüdürlüğü'],
            ['id' => 861, 'district_id' => 854, 'name' => 'Ulaş Malmüdürlüğü'],
            ['id' => 862, 'district_id' => 886, 'name' => 'Süleymanpaşa Vergi Dairesi Müdürlüğü'],
            ['id' => 863, 'district_id' => 886, 'name' => 'Namık Kemal Vergi Dairesi Müdürlüğü'],
            ['id' => 864, 'district_id' => 878, 'name' => 'Çorlu İhtisas Vergi Dairesi Müdürlüğü'],
            ['id' => 865, 'district_id' => 877, 'name' => 'Çerkezköy Vergi Dairesi Müdürlüğü'],
            ['id' => 866, 'district_id' => 878, 'name' => 'Çorlu Vergi Dairesi Müdürlüğü'],
            ['id' => 867, 'district_id' => 880, 'name' => 'Hayrabolu Vergi Dairesi Müdürlüğü'],
            ['id' => 868, 'district_id' => 882, 'name' => 'Malkara Vergi Dairesi Müdürlüğü'],
            ['id' => 869, 'district_id' => 884, 'name' => 'Muratlı Vergi Dairesi Müdürlüğü'],
            ['id' => 870, 'district_id' => 887, 'name' => 'Şarköy Vergi Dairesi Müdürlüğü'],
            ['id' => 871, 'district_id' => 881, 'name' => 'Kapaklı Vergi Dairesi Müdürlüğü'],
            ['id' => 872, 'district_id' => 885, 'name' => 'Saray Malmüdürlüğü'],
            ['id' => 873, 'district_id' => 883, 'name' => 'Marmara Ereğlisi Malmüdürlüğü'],
            ['id' => 874, 'district_id' => 892, 'name' => 'Tokat Vergi Dairesi Müdürlüğü'],
            ['id' => 875, 'district_id' => 891, 'name' => 'Erbaa Vergi Dairesi Müdürlüğü'],
            ['id' => 876, 'district_id' => 893, 'name' => 'Niksar Vergi Dairesi Müdürlüğü'],
            ['id' => 877, 'district_id' => 897, 'name' => 'Turhal Vergi Dairesi Müdürlüğü'],
            ['id' => 878, 'district_id' => 899, 'name' => 'Zile Vergi Dairesi Müdürlüğü'],
            ['id' => 879, 'district_id' => 888, 'name' => 'Almus Malmüdürlüğü'],
            ['id' => 880, 'district_id' => 889, 'name' => 'Artova Malmüdürlüğü'],
            ['id' => 881, 'district_id' => 895, 'name' => 'Reşadiye Malmüdürlüğü'],
            ['id' => 882, 'district_id' => 894, 'name' => 'Pazar Malmüdürlüğü'],
            ['id' => 883, 'district_id' => 898, 'name' => 'Yeşilyurt Malmüdürlüğü'],
            ['id' => 884, 'district_id' => 890, 'name' => 'Başçiftlik Malmüdürlüğü'],
            ['id' => 885, 'district_id' => 896, 'name' => 'Sulusaray Malmüdürlüğü'],
            ['id' => 886, 'district_id' => 912, 'name' => 'Hızırbey Vergi Dairesi Müdürlüğü'],
            ['id' => 887, 'district_id' => 912, 'name' => 'Karadeniz Vergi Dairesi Müdürlüğü'],
            ['id' => 888, 'district_id' => 900, 'name' => 'Akçaabat Vergi Dairesi Müdürlüğü'],
            ['id' => 889, 'district_id' => 911, 'name' => 'Of Vergi Dairesi Müdürlüğü'],
            ['id' => 890, 'district_id' => 916, 'name' => 'Vakfıkebir Vergi Dairesi Müdürlüğü'],
            ['id' => 891, 'district_id' => 901, 'name' => 'Araklı Malmüdürlüğü'],
            ['id' => 892, 'district_id' => 902, 'name' => 'Arsin Malmüdürlüğü'],
            ['id' => 893, 'district_id' => 905, 'name' => 'Çaykara Malmüdürlüğü'],
            ['id' => 894, 'district_id' => 910, 'name' => 'Maçka Malmüdürlüğü'],
            ['id' => 895, 'district_id' => 913, 'name' => 'Sürmene Malmüdürlüğü'],
            ['id' => 896, 'district_id' => 915, 'name' => 'Tonya Malmüdürlüğü'],
            ['id' => 897, 'district_id' => 917, 'name' => 'Yomra Malmüdürlüğü'],
            ['id' => 898, 'district_id' => 903, 'name' => 'Beşikdüzü Malmüdürlüğü'],
            ['id' => 899, 'district_id' => 914, 'name' => 'Şalpazarı Malmüdürlüğü'],
            ['id' => 900, 'district_id' => 904, 'name' => 'Çarşıbaşı Malmüdürlüğü'],
            ['id' => 901, 'district_id' => 906, 'name' => 'Dernekpazarı Malmüdürlüğü'],
            ['id' => 902, 'district_id' => 907, 'name' => 'Düzköy Malmüdürlüğü'],
            ['id' => 903, 'district_id' => 908, 'name' => 'Hayrat Malmüdürlüğü'],
            ['id' => 904, 'district_id' => 909, 'name' => 'Köprübaşı Malmüdürlüğü'],
            ['id' => 905, 'district_id' => 921, 'name' => 'Tunceli Vergi Dairesi Müdürlüğü'],
            ['id' => 906, 'district_id' => 918, 'name' => 'Çemişgezek Malmüdürlüğü'],
            ['id' => 907, 'district_id' => 919, 'name' => 'Hozat Malmüdürlüğü'],
            ['id' => 908, 'district_id' => 920, 'name' => 'Mazgirt Malmüdürlüğü'],
            ['id' => 909, 'district_id' => 922, 'name' => 'Nazimiye Malmüdürlüğü'],
            ['id' => 910, 'district_id' => 923, 'name' => 'Ovacık Malmüdürlüğü'],
            ['id' => 911, 'district_id' => 924, 'name' => 'Pertek Malmüdürlüğü'],
            ['id' => 912, 'district_id' => 925, 'name' => 'Pülümür Malmüdürlüğü'],
            ['id' => 913, 'district_id' => 863, 'name' => 'Şehitlik Vergi Dairesi Müdürlüğü'],
            ['id' => 914, 'district_id' => 863, 'name' => 'Topçu Meydanı Vergi Dairesi Müdürlüğü'],
            ['id' => 915, 'district_id' => 867, 'name' => 'Siverek Vergi Dairesi Müdürlüğü'],
            ['id' => 916, 'district_id' => 869, 'name' => 'Viranşehir Vergi Dairesi Müdürlüğü'],
            ['id' => 917, 'district_id' => 858, 'name' => 'Birecik Vergi Dairesi Müdürlüğü'],
            ['id' => 918, 'district_id' => 868, 'name' => 'Suruç  Vergi Dairesi Müdürlüğü'],
            ['id' => 919, 'district_id' => 857, 'name' => 'Akçakale Malmüdürlüğü'],
            ['id' => 920, 'district_id' => 859, 'name' => 'Bozova Malmüdürlüğü'],
            ['id' => 921, 'district_id' => 862, 'name' => 'Halfeti Malmüdürlüğü'],
            ['id' => 922, 'district_id' => 865, 'name' => 'Hilvan Malmüdürlüğü'],
            ['id' => 923, 'district_id' => 860, 'name' => 'Ceylanpınar Malmüdürlüğü'],
            ['id' => 924, 'district_id' => 864, 'name' => 'Harran Malmüdürlüğü'],
            ['id' => 925, 'district_id' => 929, 'name' => 'Uşak Vergi Dairesi Müdürlüğü'],
            ['id' => 926, 'district_id' => 926, 'name' => 'Banaz Vergi Dairesi Müdürlüğü'],
            ['id' => 927, 'district_id' => 927, 'name' => 'Eşme Vergi Dairesi Müdürlüğü'],
            ['id' => 928, 'district_id' => 928, 'name' => 'Karahallı Malmüdürlüğü'],
            ['id' => 929, 'district_id' => 931, 'name' => 'Ulubey Malmüdürlüğü'],
            ['id' => 930, 'district_id' => 930, 'name' => 'Sivaslı Malmüdürlüğü'],
            ['id' => 931, 'district_id' => 940, 'name' => 'Van Vergi Dairesi Müdürlüğü'],
            ['id' => 932, 'district_id' => 937, 'name' => 'Erciş Vergi Dairesi Müdürlüğü'],
            ['id' => 933, 'district_id' => 933, 'name' => 'Başkale Malmüdürlüğü'],
            ['id' => 934, 'district_id' => 935, 'name' => 'Çatak Malmüdürlüğü'],
            ['id' => 935, 'district_id' => 938, 'name' => 'Gevaş Malmüdürlüğü'],
            ['id' => 936, 'district_id' => 939, 'name' => 'Gürpınar Malmüdürlüğü'],
            ['id' => 937, 'district_id' => 941, 'name' => 'Muradiye Malmüdürlüğü'],
            ['id' => 938, 'district_id' => 942, 'name' => 'Özalp Malmüdürlüğü'],
            ['id' => 939, 'district_id' => 932, 'name' => 'Bahçesaray Malmüdürlüğü'],
            ['id' => 940, 'district_id' => 934, 'name' => 'Çaldıran Malmüdürlüğü'],
            ['id' => 941, 'district_id' => 936, 'name' => 'Edremit Malmüdürlüğü'],
            ['id' => 942, 'district_id' => 943, 'name' => 'Saray Malmüdürlüğü'],
            ['id' => 943, 'district_id' => 958, 'name' => 'Yozgat Vergi Dairesi Müdürlüğü'],
            ['id' => 944, 'district_id' => 953, 'name' => 'Boğazlıyan Vergi Dairesi Müdürlüğü'],
            ['id' => 945, 'district_id' => 961, 'name' => 'Sorgun Vergi Dairesi Müdürlüğü'],
            ['id' => 946, 'district_id' => 964, 'name' => 'Yerköy Vergi Dairesi Müdürlüğü'],
            ['id' => 947, 'district_id' => 951, 'name' => 'Akdağmadeni Malmüdürlüğü'],
            ['id' => 948, 'district_id' => 955, 'name' => 'Çayıralan Malmüdürlüğü'],
            ['id' => 949, 'district_id' => 956, 'name' => 'Çekerek Malmüdürlüğü'],
            ['id' => 950, 'district_id' => 960, 'name' => 'Sarıkaya Malmüdürlüğü'],
            ['id' => 951, 'district_id' => 962, 'name' => 'Şefaatli Malmüdürlüğü'],
            ['id' => 952, 'district_id' => 952, 'name' => 'Aydıncık Malmüdürlüğü'],
            ['id' => 953, 'district_id' => 954, 'name' => 'Çandır Malmüdürlüğü'],
            ['id' => 954, 'district_id' => 957, 'name' => 'Kadışehri Malmüdürlüğü'],
            ['id' => 955, 'district_id' => 959, 'name' => 'Saraykent Malmüdürlüğü'],
            ['id' => 956, 'district_id' => 963, 'name' => 'Yenifakılı Malmüdürlüğü'],
            ['id' => 957, 'district_id' => 972, 'name' => 'Uzunmehmet Vergi Dairesi Müdürlüğü'],
            ['id' => 958, 'district_id' => 972, 'name' => 'Kara Elmas Vergi Dairesi Müdürlüğü'],
            ['id' => 959, 'district_id' => 968, 'name' => 'Ereğli Vergi Dairesi Müdürlüğü'],
            ['id' => 960, 'district_id' => 966, 'name' => 'Çaycuma Vergi Dairesi Müdürlüğü'],
            ['id' => 961, 'district_id' => 967, 'name' => 'Devrek Vergi Dairesi Müdürlüğü'],
            ['id' => 962, 'district_id' => 965, 'name' => 'Alaplı Malmüdürlüğü'],
            ['id' => 963, 'district_id' => 969, 'name' => 'Gökçebey Malmüdürlüğü'],
            ['id' => 964, 'district_id' => 55, 'name' => 'Aksaray Vergi Dairesi Müdürlüğü'],
            ['id' => 965, 'district_id' => 51, 'name' => 'Ağaçören Malmüdürlüğü'],
            ['id' => 966, 'district_id' => 54, 'name' => 'Güzelyurt Malmüdürlüğü'],
            ['id' => 967, 'district_id' => 56, 'name' => 'Ortaköy Malmüdürlüğü'],
            ['id' => 968, 'district_id' => 57, 'name' => 'Sarıyahşi Malmüdürlüğü'],
            ['id' => 969, 'district_id' => 52, 'name' => 'Eskil Malmüdürlüğü'],
            ['id' => 970, 'district_id' => 53, 'name' => 'Gülağaç Malmüdürlüğü'],
            ['id' => 971, 'district_id' => 174, 'name' => 'Bayburt Vergi Dairesi Müdürlüğü'],
            ['id' => 972, 'district_id' => 172, 'name' => 'Aydıntepe Malmüdürlüğü'],
            ['id' => 973, 'district_id' => 173, 'name' => 'Demirözü Malmüdürlüğü'],
            ['id' => 974, 'district_id' => 537, 'name' => 'Karaman Vergi Dairesi Müdürlüğü'],
            ['id' => 975, 'district_id' => 533, 'name' => 'Ayrancı Malmüdürlüğü'],
            ['id' => 976, 'district_id' => 535, 'name' => 'Ermenek Malmüdürlüğü'],
            ['id' => 977, 'district_id' => 536, 'name' => 'Kazım Karabekir Malmüdürlüğü'],
            ['id' => 978, 'district_id' => 534, 'name' => 'Başyayla Malmüdürlüğü'],
            ['id' => 979, 'district_id' => 538, 'name' => 'Sarıveliler Malmüdürlüğü'],
            ['id' => 980, 'district_id' => 589, 'name' => 'Irmak Vergi Dairesi Müdürlüğü'],
            ['id' => 981, 'district_id' => 589, 'name' => 'Kaletepe Vergi Dairesi Müdürlüğü'],
            ['id' => 982, 'district_id' => 586, 'name' => 'Delice Malmüdürlüğü'],
            ['id' => 983, 'district_id' => 588, 'name' => 'Keskin Malmüdürlüğü'],
            ['id' => 984, 'district_id' => 590, 'name' => 'Sulakyurt Malmüdürlüğü'],
            ['id' => 985, 'district_id' => 584, 'name' => 'Balışeyh Malmüdürlüğü'],
            ['id' => 986, 'district_id' => 585, 'name' => 'Çelebi Malmüdürlüğü'],
            ['id' => 987, 'district_id' => 587, 'name' => 'Karakeçili Malmüdürlüğü'],
            ['id' => 988, 'district_id' => 170, 'name' => 'Batman Vergi Dairesi Müdürlüğü'],
            ['id' => 989, 'district_id' => 166, 'name' => 'Beşiri Malmüdürlüğü'],
            ['id' => 990, 'district_id' => 167, 'name' => 'Gercüş Malmüdürlüğü'],
            ['id' => 991, 'district_id' => 168, 'name' => 'Hasankeyf Malmüdürlüğü'],
            ['id' => 992, 'district_id' => 169, 'name' => 'Kozluk Malmüdürlüğü'],
            ['id' => 993, 'district_id' => 171, 'name' => 'Sason Malmüdürlüğü'],
            ['id' => 994, 'district_id' => 874, 'name' => 'Şırnak Vergi Dairesi Müdürlüğü'],
            ['id' => 995, 'district_id' => 871, 'name' => 'Cizre Vergi Dairesi Müdürlüğü'],
            ['id' => 996, 'district_id' => 875, 'name' => 'Silopi Vergi Dairesi Müdürlüğü'],
            ['id' => 997, 'district_id' => 870, 'name' => 'Beytüşşebap Malmüdürlüğü'],
            ['id' => 998, 'district_id' => 872, 'name' => 'Güçlükonak Malmüdürlüğü'],
            ['id' => 999, 'district_id' => 873, 'name' => 'İdil Malmüdürlüğü'],
            ['id' => 1000, 'district_id' => 876, 'name' => 'Uludere Malmüdürlüğü'],
            ['id' => 1001, 'district_id' => 164, 'name' => 'Bartın Vergi Dairesi Müdürlüğü'],
            ['id' => 1002, 'district_id' => 162, 'name' => 'Amasra Malmüdürlüğü'],
            ['id' => 1003, 'district_id' => 163, 'name' => 'Kurucaşile Malmüdürlüğü'],
            ['id' => 1004, 'district_id' => 165, 'name' => 'Ulus Malmüdürlüğü'],
            ['id' => 1005, 'district_id' => 114, 'name' => 'Ardahan Vergi Dairesi Müdürlüğü'],
            ['id' => 1006, 'district_id' => 110, 'name' => 'Çıldır Malmüdürlüğü'],
            ['id' => 1007, 'district_id' => 111, 'name' => 'Damal Malmüdürlüğü'],
            ['id' => 1008, 'district_id' => 112, 'name' => 'Göle Malmüdürlüğü'],
            ['id' => 1009, 'district_id' => 113, 'name' => 'Hanak Malmüdürlüğü'],
            ['id' => 1010, 'district_id' => 115, 'name' => 'Posof Malmüdürlüğü'],
            ['id' => 1011, 'district_id' => 432, 'name' => 'Iğdır Vergi Dairesi Müdürlüğü'],
            ['id' => 1012, 'district_id' => 430, 'name' => 'Aralık Malmüdürlüğü'],
            ['id' => 1013, 'district_id' => 431, 'name' => 'Karakoyunlu Malmüdürlüğü'],
            ['id' => 1014, 'district_id' => 433, 'name' => 'Tuzluca Malmüdürlüğü'],
            ['id' => 1015, 'district_id' => 949, 'name' => 'Yalova Vergi Dairesi Müdürlüğü'],
            ['id' => 1016, 'district_id' => 945, 'name' => 'Altınova Malmüdürlüğü'],
            ['id' => 1017, 'district_id' => 946, 'name' => 'Armutlu Malmüdürlüğü'],
            ['id' => 1018, 'district_id' => 947, 'name' => 'Çınarcık Malmüdürlüğü'],
            ['id' => 1019, 'district_id' => 529, 'name' => 'Karabük Vergi Dairesi Müdürlüğü'],
            ['id' => 1020, 'district_id' => 531, 'name' => 'Safranbolu Vergi Dairesi Müdürlüğü'],
            ['id' => 1021, 'district_id' => 527, 'name' => 'Eflani Malmüdürlüğü'],
            ['id' => 1022, 'district_id' => 528, 'name' => 'Eskipazar Malmüdürlüğü'],
            ['id' => 1023, 'district_id' => 530, 'name' => 'Ovacık Malmüdürlüğü'],
            ['id' => 1024, 'district_id' => 532, 'name' => 'Yenice Malmüdürlüğü'],
            ['id' => 1025, 'district_id' => 608, 'name' => 'Kilis Vergi Dairesi Müdürlüğü'],
            ['id' => 1026, 'district_id' => 776, 'name' => 'Osmaniye Vergi Dairesi Müdürlüğü'],
            ['id' => 1027, 'district_id' => 775, 'name' => 'Kadirli Vergi Dairesi Müdürlüğü'],
            ['id' => 1028, 'district_id' => 772, 'name' => 'Bahçe  Malmüdürlüğü'],
            ['id' => 1029, 'district_id' => 773, 'name' => 'Düziçi Malmüdürlüğü'],
            ['id' => 1030, 'district_id' => 774, 'name' => 'Hasanbeyli Malmüdürlüğü'],
            ['id' => 1031, 'district_id' => 777, 'name' => 'Sumbas Malmüdürlüğü'],
            ['id' => 1032, 'district_id' => 778, 'name' => 'Toprakkale Malmüdürlüğü'],
            ['id' => 1033, 'district_id' => 315, 'name' => 'Düzce Vergi Dairesi Müdürlüğü'],
            ['id' => 1034, 'district_id' => 309, 'name' => 'Akçakoca Vergi Dairesi Müdürlüğü'],
            ['id' => 1035, 'district_id' => 310, 'name' => 'Cumayeri Malmüdürlüğü'],
            ['id' => 1036, 'district_id' => 311, 'name' => 'Çilimli Malmüdürlüğü'],
            ['id' => 1037, 'district_id' => 312, 'name' => 'Gölyaka Malmüdürlüğü'],
            ['id' => 1038, 'district_id' => 313, 'name' => 'Gümüşova Malmüdürlüğü'],
            ['id' => 1039, 'district_id' => 314, 'name' => 'Kaynaşlı Malmüdürlüğü'],
            ['id' => 1040, 'district_id' => 316, 'name' => 'Yığılca Malmüdürlüğü'],
        ];
        TaxDepartment::insert($taxDepartmentLists);
    }
}
